### ISSUE TITLE
Use cached cmake-file-api response to configure IntelliSense on startup

### ISSUE THREAD

**Issue by ghuser404** [microsoft/vscode-cmake-tools#1149]
I have `configureOnOpen` set to false, because I don't want it to happen automatically. However, I still expect to not see red squiggles when i open my project. To make them go away I need to configure project every time I open it.

The errors are with includes: this show for first unrecognized include `#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\foo.cpp).` and this show for every include `cannot open source file "include/bar.h"`

**Comment by bobbrow** [comment]
That is currently the designed behavior.  CMake needs to configure in order for the code model to be generated so that IntelliSense configurations can be provided.  This is also the root cause for your other issue #1148.

We need to do the work to persist the configurations.  Fortunately, with cmake-file-api (CMake 3.14.6+), they are already persisted.  We could easily just re-read them if the configure step has not happened yet.

**Comment by ghuser404** [comment]
Yeah, I figured they are somewhat related. I probably wouldn't be as concerned if configuring a project would be a little easier, i.e. currently it's select CMake Tools extension -> press configure -> go back to Explorer view. I particularly don't like switching between views just to configure project. Another way, of course, is to use variants, i.e. press on variants -> select variant. But that requires to go through the list of variants and press on the one that you were previously working. Maybe there is an easier method that I just don't know about.

Overall, I'm quite happy with the extension, but I just think UI could be a bit better :)

**Comment by KyleFromKitware** [comment]
+1 for reading from the existing File API response on startup.
