### ISSUE TITLE
Specifying C/C++ standard with target_compile_features is very inconsistent

### ISSUE THREAD

**Issue by ghuser404** [microsoft/vscode-cmake-tools#1152]
To detect selected C/C++ standard, I used "C/C++: Log Diagnostics". I didn't find any issue when specifying standard with `CMAKE_C_FLAGS` or `CMAKE_CXX_FLAGS`.
I used gcc 5.4.0 on WSL and on Windows (via mingw-w64).

1. When I specify `target_compile_features(test PRIVATE cxx_std_98)`, cpptools reports c++17 - I had this issue only on WSL, not on Windows. 

2. If I don't specify C++ standard, cpptools always reports c++17, but gcc 5.4.0 doesn't default to that. This is both on Windows and WSL.

3. If I specify any of `c_std_90`, `c_std_99`, `c_std_11` , cpptools always reports c11. This is only on WSL, not on Windows.

UPDATE: when I updated cmake on Windows to the same version that is on WSL (3.16.5), I started getting the same behaviour on Windows, as on WSL.

**Comment by andreeis** [comment]
We need to double check the defaults implemented in CMake Tools, possibly separate cases for different compilers. This targets bullet 2.

For bullets 1 and 3, I did not try on WSL or Mingw but I suspect the inconsistency is also caused by cmake by not generating any -std switch (I don't know why yet and it's also not relevant for fixing this) and so the extension sees no standard flag to parse (which is bullet 2 basically). On simple windows (not mingw) I notice while debugging that the CMake Tools extension sees no standard flag for cxx_std_98, c_std_90, c_std_99. For c_std_11 or cxx_std_17, the extension will get an extra standard flag passed in. It's possible for WSL that cmake would not generate this flag and on mingw it would.

**Comment by ghuser404** [comment]
Hmm, maybe the cmake version on Windows and WSL are different, which causes this difference in behaviour. I'll check that later.

**Comment by ghuser404** [comment]
I actually had very different versions of cmake on Windows and WSL: 3.12 and 3.16.5. I upgraded cmake on Windows to 3.16.5 (and now to 3.17), and see exactly the same behaviour that I had on WSL. So after all, behaviour wasn't different because of WSL, but because of different cmake versions. So it seems CMake Tools doesn't handle newer cmake version correctly.
