### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by brechtvb** [microsoft/vscode-cmake-tools#1171]
- Issue Type: `Performance`
- Extension Name: `cmake-tools`
- Extension Version: `1.3.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.44.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\ms89w8\
[ms-vscode.cmake-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cmake-tools/files/4466710/ms-vscode.cmake-tools-unresponsive.cpuprofile.txt)
cmake-tools/files/4466709/ms-vscode.cmake-tools-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Terafugia** [comment]
I think I might be experiencing the same problem. I'm going to apologise in advance in case I am wrong (sorry). I've attached my CPU-profile.

[ms-vscode.cmake-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cmake-tools/files/4484698/ms-vscode.cmake-tools-unresponsive.cpuprofile.txt)

**Comment by bobbrow** [comment]
@brechtvb, your issue looks like CMake Server sending a lot of data back to the extension.  Do you have a large project?  I'm afraid there's not much we can do about that issue.  You could try to upgrade CMake to 3.14.6 or higher and use the CMake File Api mode instead of CMake Server to mitigate the problem.

@Terafugia, your issue looks like setting up the MSVC environment took more than 5 seconds.  I'm not sure what would cause that.  If you launch the "Developer Command Prompt" from the Start Menu in Windows, does it normally take a few seconds for the prompt to appear?
