### ISSUE TITLE
No contributing guide found

### ISSUE THREAD

**Issue by vptrbv** [microsoft/vscode-cmake-tools#1262]
I'd like to contribute - but stuck at push to remote repo (as I've added it [with](https://opensource.com/article/19/7/create-pull-request-github) this guide). 
Assistance or guide wanted.

**Comment by vptrbv** [comment]
My bad, not deserves an issue

**Comment by bobbrow** [comment]
Sorry about that.  We have some work to do on the documentation and the docs posted by `vector-of-bool` who maintained this project previously have gotten out of date (we use `yarn install` instead of `npm install` to configure the extension now).

It looks like you were able to figure out what you needed, but please let us know if you have any other questions.
