### ISSUE TITLE
Build type selection not honoring `CMAKE_CONFIGURATION_TYPES`

### ISSUE THREAD

**Issue by seanmiddleditch** [microsoft/vscode-cmake-tools#128]
I have set `CMAKE_CONFIGURATION_TYPES` in my `CMakeLists.txt` but cmake-tools does not seem to be honoring it entirely in the UI. In the build type selection dropdown, for instance, I always see the four default CMake configurations.

This is with the cmake-server enabled. The build configuration dropdown is always empty for me with it turned off.

**Comment by vector-of-bool** [comment]
The extension used to respect `CMAKE_CONFIGURATION_TYPES`, but it rare for users to customize that setting. With the addition of the variants feature, it dropped by the wayside. Currently, if there is no `cmake-variants` file in a project, the four common defaults are hardcoded in. It would be useful to fall back on `CMAKE_CONFIGURATION_TYPES` instead, but I'm not sure how much work would be required.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.

**Comment by tonka3000** [comment]
Hey @bobbrow,

This is still an issue in 1.14.0. It would be very nice when the dropdown menu will have only valid configurations after configure (should be available via cmake-server).

Can you please reopen this issue because for me that is a feature-request.

## Usecase
I know many projects which use these values to force single config in multi config generators, including myself :smile: . A example-code for that would be
```cmake
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "Choose the type of build." FORCE)
endif()
if(CMAKE_BUILD_TYPE)
  set(CMAKE_CONFIGURATION_TYPES ${CMAKE_BUILD_TYPE})
endif()

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

foreach(_config_type ${CMAKE_CONFIGURATION_TYPES})
    string(TOUPPER ${_config_type} _config_type)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${_config_type} "${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${_config_type} "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${_config_type} "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
endforeach()
```

But I'm not aware of an projects which use a custom config value like `myownconfig` instead of default ones `Debug`/`Release`/...

## Expect behavior
* Without configure the hardcoded values are fine
* After configure the dropdown should only contain values of `CMAKE_CONFIGURATION_TYPES` (hide/deactivate buttons or something like that)
* If `CMAKE_CONFIGURATION_TYPES` is empty, just display the 4 default ones.

Thanks in advance  
Tonka

**Comment by bobbrow** [comment]
Sure, I can reopen this.  But to be totally transparent, it will probably be a while before we get to this.  If anyone wants to take a crack at implementing this, they are welcome to contribute.

**Comment by tonka3000** [comment]
Hey @bobbrow ,

I've thought about that issue for a while now to maybe make a PR.

The interessting part is the just setting the `CMAKE_BUILD_TYPE` in multi config generator would make the problem much smaller. I've search for `CMAKE_BUILD_TYPE is not set` issue in the issue tracker and it seems that there are a lot of questions about it. So I've just add a comment to this post instead of create another `CMAKE_BUILD_TYPE is not set` issue, but maybe the discussion is better in another issue.

When setting `CMAKE_BUILD_TYPE` in f.e. Visual Studio generator there are only two things which I can think of what could go bad
- user get single config instead of multi config, when I project, like my ones, react on the define<br>
  But I think that is not that hard for a VS Code user because right now the actual configs are hardcoded, so the user would not mention it that much
- A CMake project (own or 3rdparty) check single config based on that flag which maybe could lead to a "wrong desicion" in the cmake like f.e. assuming it is gcc, mingw or something in that category

I would love to see `CMAKE_BUILD_TYPE` set in multi config generators and also set the `--config` argument (`cmake --build`) in that case, because it make the UX  much better, especially on Windows. Right now I set the config in my `settings.json` file which often not set to the same parameter as config from your cmake integration, which I always had to check if it is the same.
I would be also fine when their would be a setting (something like `"cmake.setBuildTypeOnMultiConfig" : true`, be default `false`), so that I can set this switch globally, so we could know if this switch does not break to much.

Greetings<br>
Tonka
