### ISSUE TITLE
Unique settings between Windows and WSL

### ISSUE THREAD

**Issue by sebastient** [microsoft/vscode-cmake-tools#1307]
Is there a way to have Windows and WSL using different CMake settings, for example the default build directory so that switching a project back and forth would not require clearing out the cache and rebuilding?

**Comment by bobbrow** [comment]
There are a couple of variables you can use to change the build directory based on the state of the extension.

You might try:
```
  "cmake.buildDirectory": "${workspaceFolder}/${buildKit}"
```

Most variables are documented here: https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html#variable-substitution, but since we don't have push access to that site, we're in the process of migrating docs back to the repository.
