### ISSUE TITLE
Unable to determine what CMake generator to use

### ISSUE THREAD

**Issue by DMirella** [microsoft/vscode-cmake-tools#1325]
Hi, I faced this problem when I opened my cmake project yesterday:
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.

Before, two days ago, all worked correctly. I can use cmake generator from Windows Prompt console.
Please help

**Comment by andreeis** [comment]
What generator are you using? What kit?
Can you share any "cmake.generator" and "cmake.preferredGenerators" settings you may have defined, at folder/workspace/global levels? Or you didn't set anything specifically anywhere?
Can you share a debug log (set in settings with "cmake.loggingLevel": "debug") for when you open and configure your project?

Try to delete the build folder and reload your project. But do this after copy pasting the above, because in case you happen to get unblocked we would lose the information that would help us identify a possible bug.
