### ISSUE TITLE
Weird behavior of configureOnOpen with external source directory

### ISSUE THREAD

**Issue by skhrshin** [microsoft/vscode-cmake-tools#1386]
### Brief Issue Summary

When cmake.sourceDirectory is set to a place which is not under the workspace directory, CMake Tools doesn't start configuration automatically after opening VSCode even though cmake.configureOnOpen is set to true. But the first time you invoke configuration manually, CMake Tools double-runs configuration and you'll get an error "Configuration is already in progress."

Similar to #783

### Steps to reproduce:

1. Create a workspace directory. (e.g. D:/Projects/_test/codetest/workspace here)
2. Write .vscode/settings.json like below

```
{
    "cmake.configureOnOpen": true,
    "cmake.cmakePath": "C:/Program Files/CMake/bin/cmake.exe",
    "cmake.buildDirectory": "D:/Projects/_test/codetest/build",
    "cmake.generator": "Ninja",
    "cmake.configureSettings": {
        "CMAKE_MAKE_PROGRAM": "C:/Development/depot_tools/ninja.exe"
    },
    "cmake.sourceDirectory": "D:/Projects/_test/codetest/src",
}
```

3. Put appropriate CMakeLists.txt under the source directory specified in .vscode/settings.json.
4. Open the workspace directory with VSCode.

### Expected:

CMake configuration runs at startup automatically.

### Apparent Behavior:

Configuration doesn't run automatically. After invoking configuration manually, "Configuration is already in progress." error is shown.

### Platform and Versions

- **Operating System**: Windows Pro x64
- **CMake Version**: 3.17.3
- **VSCode Version**: 1.47.2
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**: Visual C++ 2017 Express

### Other Notes/Information

As workaround, putting a dummy CMakeLists.txt under the workspace directory solves the problem.

**Comment by bobbrow** [comment]
Because the CMakeLists.txt is outside of the workspace folder, VS Code doesn't end up activating the CMake Tools extension until you run the configuration command.  The extension doesn't know the condition that activates it and ends up trying to configure again.  We'll see if there is anything we can do to detect this case and prevent it.  Your workaround sounds like exactly the right thing to trick VS Code and the extension into doing the right thing for now.
