### ISSUE TITLE
Tool kit not update after create .vscode/cmake-kits.json on new workspace/folder.

### ISSUE THREAD

**Issue by alan-wr** [microsoft/vscode-cmake-tools#1416]
### Brief Issue Summary

Tool kit not update after create .vscode/cmake-kits.json on new workspace/folder.

sample:

[
  {
    "name": "Tools Kit new 3",
    "toolchainFile": "/buildarea/toolchain.cmake"
  }
]

'CMake: Scan for Kits' cannot help.

Workaround : remove the folder from workspace and add it again.

### Expected:

'CMake: Scan for Kits' can update tool kit.

### Apparent Behavior:

'CMake: Scan for Kits' do not update tool kit.

### CMake Tools Log

```
<!-- Paste the log contents HERE -->
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.48.0
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**: toolchainfile

**Comment by ChaseLewis** [comment]
Is this the bug why a toolchain parameter isn't being added on configure? Trying to get vcpkg to work, but nothing I do gets the build command to add itself like the documentation says it should.

**Comment by andreeis** [comment]
This is a bug about a new cmake-kits.json being added in the .vscode subfolder of one of the projects currently loaded by VSCode. Edits to such file are not detected because the file watchers don't work properly on something that wasn't existing when the file watchers were registered. This goes away after the next project reload after the new cmkae-kits.json is created.

Your problem does not sound like it gets fixed with a reload. Please open a new issue and try to craft a small standalone repro for us that would help speed up our investigation.

Also, does the same happen for you when you add a toolchain file in a kit defined in the user kits file, instead of a .vscode/cmake-kits.json?
