### ISSUE TITLE
Disable '--config Debug' option in cmake

### ISSUE THREAD

**Issue by moonlight16** [microsoft/vscode-cmake-tools#1436]
When I'm building my project, I see this command being executed in the output:

    [proc] Executing command: /usr/bin/cmake3 --build /root/<project-name>/base/build --config Debug --target all -- -j 4

And I get a ton of build errors.

I'm still new to cmake but normally my project builds fine with this:

    /usr/bin/cmake3 CMakeLists.txt
    make -j4

I'm finding it difficult to find a way to remove the `--config Debug` and other settings in the cmake3 command.  The documentation only talks about adding Debug variants, but its not clear how to control the parameters of the command itself.  My settings don't have any command options listed.

Please help.

**Comment by bobbrow** [comment]
Sorry for the delay in responding... What kinds of errors are you seeing?

**Comment by moonlight16** [comment]
I no longer have this environment setup.  I recall it wasn't very clear how to remove this `--config Debug` options using the integrated cmake with vscode.  The docs and settings weren't clear on how to remove.

**Comment by bobbrow** [comment]
I'm mostly surprised that you're seeing errors with this, because it's been this way since before we started maintaining the project.  `--config Debug` should be harmless for single-config generators (unless perhaps you generated a different variant and did not reconfigure the project for "Debug", in which case this error would be helpful and let you know that you're not working with the variant you expected).

If you have any trouble with this again in the future, please let us know, and again, I'm sorry for the delay in responding earlier. ☹️
