### ISSUE TITLE
CMake Build Directory per project

### ISSUE THREAD

**Issue by zethon** [microsoft/vscode-cmake-tools#1453]
### Brief Issue Summary

Support a custom CMake build directory per project

### Other Notes/Information

I use Visual Studio Code for multiple projects, not all of which share the same CMake Build Directory location. When I switch between projects, if I want to use the CMake tools built into Visual Studio Code I have to go into my preferences and change:

![image](https://user-images.githubusercontent.com/5203583/94035440-0f7a9b00-fd91-11ea-8785-4abcbf6823e8.png)

It would be great if I could configure this on a per project basis.

**Comment by bobbrow** [comment]
You should be able to do this by changing the value of the `Workspace` setting instead of the `User` setting.  User settings apply to all workspaces, while workspace settings only apply to the current workspace.

![image](https://user-images.githubusercontent.com/12818240/95769229-67a80d00-0c6c-11eb-8333-31d3e02d5c6a.png)
