### ISSUE TITLE
c11 is being used instead of gnu17

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cmake-tools#1477]
See the repro at https://github.com/microsoft/vscode-cpptools/issues/6279 .

**Comment by andreeis** [comment]
Possibly related https://github.com/microsoft/vscode-cmake-tools/issues/1489.

**Comment by Colengms** [comment]
This issue is due to falling back to a hard-coded default, and not querying the compiler to determine what its default actually is.  To avoid requiring all config providers from having to do this, we've made a change to the cpptools-api to allow IntelliSenseMode, cStandard and cppStandard to be omitted, and automatically determined by cpptools based on the compilerPath and compilerArgs.  I think we have some other changes we'd like make to the API before publishing a new version.  Once a new version of cpptools-api is published, CMake Tools can be updated to omit these fields.
