### ISSUE TITLE
CMake builds launch target once per every "${command:cmake.launchTargetXXX}" reference

### ISSUE THREAD

**Issue by dslijepcevic** [microsoft/vscode-cmake-tools#1487]
### Brief Issue Summary

It seems that `${command:cmake.launchTargetDirectory}`, `${command:cmake.launchTargetFilename}` and `${command:cmake.launchTargetPath}` are evaluated more than once when launching a configuration. When `cmake.buildBeforeRun` is `true` these commands will ensure that launch target exists before evaluating its properties, but the unfortunate side-effect is that the target will get built once per each command reference. This means that if you reference all 3 of them in a launch configuration in `launch.json` and then once again within the `preLaunchTask` in `tasks.json`, your launch target will get built 6 (*six*) times! And all 6 times you get full output text as well as extension pop-ups about compiling.

I guess this may have been implemented like this for simplicity, but I would still optimize this down to building the launch target exactly _once_ when `cmake.buildBeforeRun` is `true`. I believe it should be possible since CMake Tools is fully in charge of the build process.

![cmake-build-multiple-times](https://user-images.githubusercontent.com/1915869/96032430-ee244080-0e5e-11eb-8a23-1ac1b941066a.gif)

**Comment by bobbrow** [comment]
Yeah, that's pretty bad.  It seems that the underlying cause is simply that a function written with the intent to prepare binaries for debug/launch was reused to get the current launch target.  If you need a quick fix before we update the extension, you can patch the `main.js` file under `~/.vscode/extensions/ms-vscode.cmake-tools-1.4.2/dist`.

**line 42520** would change from `chosen = current;` to `return current;`. This will exit the function early and skip configuration/build which is unnecessary for these commands.

![image](https://user-images.githubusercontent.com/12818240/96037330-8cda7e00-0e1a-11eb-8c0c-9b768c1c5b3b.png)

**Comment by dslijepcevic** [comment]
Hmm, with that modification I think it behaves as if `cmake.buildBeforeRun` is set to `false`. Oh, and also, I don't see these 3 commands in question documented in a single place anywhere.  Even extension's Feature Contributions are showing %% in place of descriptions:

![image](https://user-images.githubusercontent.com/1915869/96050908-c216b880-0e7a-11eb-9948-713fa32529dc.png)

**Comment by bobbrow** [comment]
Sorry about that.  I meant to reply back and say that my suggestion wouldn't work for some cases because this function is called in some other scenarios that I didn't realize.  I was working on an alternate fix but got pulled away into a few meetings.  You'll want to revert any code changes you made in main.js for now.

**Comment by bobbrow** [comment]
Regarding documentation, I thought we had documented this, but I'm not finding a specific page for it.  I think we should update [cmake-settings.md](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/cmake-settings.md) and add all the supported commands.  I also see some references in [debug-launch.md](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/debug-launch.md)

The %% showing in the feature contributions is a vscode bug.  https://github.com/microsoft/vscode/issues/54111

**Comment by dslijepcevic** [comment]
Well, we tried, no worries. But while we're at it, I have a suggestion for a new command: `${command:cmake.buildTargetName}`. Should not be too hard to implement I think. It would be useful if you want to perform a build using a task (for example, with `cmake.buildTask` set to `true`), but you'd still like to use some of CMake Tools's cool features like active build target. Thanks.

**Comment by andreeis** [comment]
This should be fixed in CMake Tools 1.5.0 which was published today.
Let us know if you encounter any issues with this release.
