### ISSUE TITLE
Confusing guidance around cmake settings

### ISSUE THREAD

**Issue by vadi2** [microsoft/vscode-cmake-tools#1553]
### Brief Issue Summary

If I want to pass an argument to CMake, I can use `-D` on the command line or on CLion, via the [UI pretty easily](https://wiki.mudlet.org/images/3/3c/CLion_CMake_settings_-_finidng_Qt.png).

In CMake Tools, the guidance is rather confusing. While it is clear that `cmake.configureSettings` should be used in settings.json, what is the UI equivalent of it?

The configure settings in the UI is not a nice tabulated view:

![image](https://user-images.githubusercontent.com/110988/99382062-399d9480-28cc-11eb-8e8d-84ea9f4919fb.png)

The Configure Environment, for my purposes, seems to work just as well - but is that the recommended approach?

**Comment by andreeis** [comment]
There is no custom UI currently for CMake configure settings or arguments. We would like to implement such feature sometime in future (not very soon since we have other asks to address first) so I am leaving this GitHub issue open to track that.

An additional clarification, use cmake.configureSettings for CMake defines (-D arguments) and cmake.configureArgs for any kind of CMake arguments (-D or not).

**Comment by vadi2** [comment]
For the record the docs for cmake.configureArgs say `Do not pass -D arguments using this setting.` which is confusing.

**Comment by bobbrow** [comment]
I just updated the docs to instead say that it is not recommended to pass -D args via `cmake.configureArgs`
