### ISSUE TITLE
[Suggestion] Transfer the extension's settings from the status bar to the side bar

### ISSUE THREAD

**Issue by songyang-dev** [microsoft/vscode-cmake-tools#1582]
Hello, the current CMake extension populates the bottom status bar a lot. It would be nice if all of those settings went into the side bar.

![image](https://user-images.githubusercontent.com/10444460/101205395-8f4b9e00-363b-11eb-9452-abdce1733b94.png)

## Version
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by bobbrow** [comment]
Yes, this is something we've been thinking about, but I don't believe an issue was created.  Thank you.  We'll use this one.

Note, we do have settings to control the status bar icons.  Take a look at `cmake.statusbar.visibility` and `cmake.statusbar.advanced` settings.

**Comment by Zingam** [comment]
When designing the new UI please consider the following:

## Configuration & Build

Each workflow (CMake presets, Kits) should have their own UI design, which makes sense in the respective context. For example for CMake presets the order of UI elements should be:

1. Active folder
2. Configure preset
3. Build preset
4. Default Build Target
5. Build
6. Launch Target
7. Debug
8. Launch

I'm not sure about the Test Preset location. 

Additionaly in CMake 3.25.0 (Presets V6) there are::

> The [cmake-presets(7)](https://cmake.org/cmake/help/git-stage/manual/cmake-presets.7.html#manual:cmake-presets(7)) schema version has been bumped to 6.
>
>  The [cmake-presets(7)](https://cmake.org/cmake/help/git-stage/manual/cmake-presets.7.html#manual:cmake-presets(7)) format now supports a packagePresets field to specify presets for [cpack --preset](https://cmake.org/cmake/help/git-stage/manual/cpack.1.html#cmdoption-cpack-preset).
>
>  The [cmake-presets(7)](https://cmake.org/cmake/help/git-stage/manual/cmake-presets.7.html#manual:cmake-presets(7)) format now supports a workflowPresets field to specify presets for [cmake --workflow](https://cmake.org/cmake/help/git-stage/manual/cmake.1.html#cmdoption-cmake-workflow).

## Debugging

Also I'd like to be able to select in the same panel the "launch" configuration (the same as in the debug panel). The Build/Launch actions should be integrated/unified with the one from the debug panel.

I'd like that a debugging/running session of unit tests (I use the C++ Mate extension) or the application targets to configurable with a launch.json. There should be just one default workflow. It doesn't seem to be the case at the moment.

**Comment by Zingam** [comment]
> Yes, this is something we've been thinking about, but I don't believe an issue was created. Thank you. We'll use this one.
> 
> Note, we do have settings to control the status bar icons. Take a look at `cmake.statusbar.visibility` and `cmake.statusbar.advanced` settings.

Are you thinking about a new panel or these we'll be added to the existing Run & Debug panel?
IMO I feel that this panel is a bit tight during debugging.

**Comment by saierd** [comment]
I just got the pre-release where the status bar buttons were removed.

Could this please be an option? I think the status bar buttons were perfectly fine as they were, especially in compact mode. Now my status bar is completely empty and I am missing the functionality that I used there all the time.

I don't use the CMake sidebar and never have it open. For me it is not really a replacement for the status bar buttons, since

* The sidebar requires much more space when it is open.
* Even if you have the sidebar open, using the CMake sidebar requires switching away from whatever sidebar you have open otherwise.

**Comment by pm-ur** [comment]
> I just got the pre-release where the status bar buttons were removed.
> 
> Could this please be an option? I think the status bar buttons were perfectly fine as they were, especially in compact mode. Now my status bar is completely empty and I am missing the functionality that I used there all the time.
> 
> I don't use the CMake sidebar and never have it open. For me it is not really a replacement for the status bar buttons, since
> 
> * The sidebar requires much more space when it is open.
> * Even if you have the sidebar open, using the CMake sidebar requires switching away from whatever sidebar you have open otherwise.

The new layout would certainly help with the real-estate while the status bar real-estate is a prime estate. However, I'd certainly love to have the option to continue showing the elements I need in the status bar. There are things we need to see or click a lot more frequently and without the status bar UI, it's become obscure and difficult. The number of clicks needed have increased and now the useful information (like the build type or default build target) stays hidden until you open the sidebar. 

Also, to interact with any of the options, the "edit" button is much smaller now. The text button is status bar was wider and easier to click especially for some common operations. It'd be great if you could make the whole row clickable in sidebar instead of just the small "edit" button. Or at least, allow increasing the width and height of the buttons to run/test/edit, etc.

**Comment by snehara99** [comment]
this is in pre-release currently
