### ISSUE TITLE
Configuring VS generator via settings.json gives no IntelliSense

### ISSUE THREAD

**Issue by ghuser404** [microsoft/vscode-cmake-tools#1584]
I set CMake Kit to Unspecified and specify generator in settings.json like so:
```
"cmake.generator": "Visual Studio 16 2019",
"cmake.platform": "Win32",
"cmake.toolset": "v140"
```
Build works correctly, but all `#include`s are red-squiggled. Using `C/C++: Log Diagnostics` shows no include paths that are specified in CMake.

However, if I create a CMake Kit and use it, then IntelliSense works correctly:
```
{
  "name": "Visual Studio Community 2019 Release - x86 (v140)",
  "visualStudio": "e1ef39ae",
  "visualStudioArchitecture": "x86",
  "preferredGenerator": {
    "name": "Visual Studio 16 2019",
    "platform": "win32",
    "toolset": "v140"
  }
}
```
PS. That is with `"configurationProvider": "ms-vscode.cmake-tools"`.

**Comment by andreeis** [comment]
Thank you for opening this issue. We will investigate what's going on and get back to you.

**Comment by andreeis** [comment]
I am not able to reproduce the IntelliSense squiggles, but I do see a notification error message (about compiler not being recorded in the cache) on the bottom right with only your scenario, so some common root cause must be between this symptom and what you are seeing. All else works fine, as you also mention. Do you see such notification error message as well?

**Comment by ghuser404** [comment]
Yes, there is also the error message. But I checked, I still have all `#include`s red-squiggled (except standard headers, they work fine, it seems).
