### ISSUE TITLE
intellisense not working sometimes

### ISSUE THREAD

**Issue by SteinsElite** [microsoft/vscode-cmake-tools#1599]
### Brief Issue Summary
i use cmake-tool as c_cpp provider of intellisense, but now i have 2 hpp file in the same level folder but different,and they both include an another hpp file in my project,it turn out one could include success and another will fail with can't open the source file.
when i remove the cmake.tool and use compile_command.json in the cpp_tool, it works well

i use mac &remote to ubuntu,
compile use clang6.0.0 kit

**Comment by andreeis** [comment]
Interesting. 
Can you share the fragments related to the 2 hpp files in compile_commands.json (or the whole file if it's more convenient).

Then:
1. set loggingLevel to debug for both CMake Tools and CppTools extensions, in your project settings.
2. Close all editors, reload your project, let it finish configuring
3. Empty the CppTools output channel so that we don't have to scran through what happened earlier.
4. Now, open one HPP.
5. When CppTools output channel is not printing anything copy and paste somewhere. 
6. Run command "C/C++: Log Diagnostics" from pallette and copy/paste the output from C/C++ Log Diagnostics output channel.
7. Empty C/C++ and Logs Diagnostics output channels.
8. Repeat 4-5-6 for the second hpp.
9. Share the outputs you saved.

Hopefully we'll figure out what's going on.

**Comment by SteinsElite** [comment]
thank for replying, i do as your suggestion,and figure out the question.when i try to search one hpp in the compile_command.json,i can't find it,then i found that i just the project just include cpp,and no cpp include that hpp,so it won't appear in the compile_command.json.
