### ISSUE TITLE
How to specify active kit in settings.json?

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#1637]
I want to build a C++ Windows desktop project using VS Code, using CMake. I can build it on the command line using Build Tools for Visual Studio 2019 + Ninja.

I can also build it in VS Code using active kit 'Visual Studio Professional 2019 Release - amd64' but I have a couple of questions:

1) When working from the command line I just specify the C++ compiler directly: 

    `-DCMAKE_CXX_COMPILER=cl`

Is it more correct to use an active kit, instead, with cmake-tools?

2) Can I specify the active kit in settings.json or should I use a toolchain?

3) If I also use Ninja, I find that there are no links for warnings and errors in the output window, so I'm using the default, which I assume is msbuild. Is this a bug?

**Comment by andreeis** [comment]
We recommend using an active kit because this will also setup the environment for the compiler defined for that kit. For example, for Visual Studio, it will run the proper vcvars batch script for you.
A toolchain or the define -DCMAKE_CXX_COMPILER=cl would work only from a Visual Studio terminal, not from a regular one.

With the current implementation of the extension, the current active kit is not saved in settings but in the project workspace state.

Regarding bullet 3, we already have a set of different issues for Ninja generator. One of them is https://github.com/microsoft/vscode-cmake-tools/issues/495. As the last comment from the community explains, try a workaround to run the build from the terminal, in the build subfolder, to have the ability of clicking on relative paths.

Another issue is around the problem matcher. There are other reports mentioning that with Ninja generator the problems tab does not have entries for the errors and warnings. Let us know if that is your case. Hopefully you are able to easily access the source locations of errors/warnings via the problems tab.

About the default generator for a Visual Studio Kit, it used to be "Ninja", we changed it to "Visual Studio" (so yes to your question, msbuild is the default) but as some users requested, we'll provide also a mechanism to default to Ninja as before: https://github.com/microsoft/vscode-cmake-tools/issues/1347.

**Comment by DavidA2014** [comment]
@andreeis Thanks for your reply. I'm not sure that this issue needs to be kept open as a bug report as the issues raised seem to be under review elsewhere.
