### ISSUE TITLE
Enabling auto build

### ISSUE THREAD

**Issue by SelvamArul** [microsoft/vscode-cmake-tools#1647]
This is not an issue per se. I just need some help in configuring cmake tools to build projects automatically as I type. I am impressed by the [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens) extension. It would be really helpful to build project automatically in the background and let Error lens display error notes inline. Currently, I am triggering the build manually. Is it possible to trigger cmake build automatically while I type or at least automatically on saving the file?

**Comment by andreeis** [comment]
Thank you for this feature idea, it sounds very interesting. We may not be able to implement it immediately and we will monitor the reactions from the community so that we find where this would fit in our backlog.
A similar but limited behavior you should get from the CppTools extension, which CMake Tools works with. It produces errors/warnings squiggles in real time by repeatedly invoking a compiler (with the appropriate switches seen by CMake) on the currently opened C/C++ source file. It is not invoking the real CMake build operation that may trigger more errors/warnings. That will be interesting to look at in future.

**Comment by SelvamArul** [comment]
Thanks for labeling this as a feature request :)

**Comment by gcampbell-msft** [comment]
It's not likely that we are going to get around to implementing this. One reason is that depending on how long a build lasts, it might not work for us to automatically have builds happen while editing if builds take too long. I'm going to close this as not planned. Thanks for the request and please open more as you have them!
