### ISSUE TITLE
CMake variant variables not expanded in c_cpp_properties

### ISSUE THREAD

**Issue by artyeffem** [microsoft/vscode-cmake-tools#1651]
### Brief Issue Summary
Using build variants specified in _cmake-variant.json_, and I expected these to be expanded the _includePath_ stanza of _c_cpp_properties.json_ so Intellisense can find auto-generated header files.

### Expected:

1. Configure variants in cmake-variant.json
2. Configure _includePath_ in c_cpp_properties.json, adding "${workspaceFolder}/${variant.platformName}/*"
3. Select CMake variant from status bar
4. Intellisense resolves build path (i.e. variant:platformName) to find auto-generated (per CMake) headers

**Note**: The build path is configured in the _settings.json_, and this variant variable is properly expanded
"cmake.buildDirectory": "${workspaceFolder}/${variant:platformName}",

### Apparent Behavior:

#include errors detected based on information provided by the configurationProvider setting. Squiggles are disabled for this translation unit (/home/artyeffem/workspace/project/src/blemgr/src/blemgr.c).

The variant-defined build path is not used.  This include error is resolved if I replace the variant line with hardcoded path in the _includePath_ stanza.

### Platform and Versions

- **Operating System**: Windows 10, Ubuntu 16.04 and 20.04
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.54.0-insider
- **CMake Tools Extension Version**: 1.5.3
- **Compiler/Toolchain**: Clang 4.0.12 with armv7m target

**Comment by bobbrow** [comment]
`c_cpp_properties.json` is not interpreted by vscode as it is an extension-specific configuration file (the C++ extension owns it).  It does not resolve CMake Tools' variables right now.

The better way to configure IntelliSense is to set the `configurationProvider` field in `c_cpp_properties.json` to `"ms-vscode.cmake-tools"` and then the C++ extension will just ask CMake Tools what the current IntelliSense configurations should be on a per-file basis - which should be more accurate than setting `includePath` globally for all files.  If the configuration provider is not working for you, we'd like to know about it so that we can make it better.
