### ISSUE TITLE
suggestion: remove -T flag when running CTest

### ISSUE THREAD

**Issue by leungyauming** [microsoft/vscode-cmake-tools#1707]
## Current

CMake Extension will run CTest with flag -T when running tests through status bar.
And this will lead to `Cannot find file: D:/Projects/cpp/bound/build/DartConfiguration.tcl`.

## Suggestion

Remove -T flag when running tests.

**Comment by sureshjoshi** [comment]
I don't know if this is a new bug, but it's definitely been a problem for me on two computers right now. The DartConfiguration.tcl can be found, assuming that `include (CTest)` exists in CMakeFiles.txt, but the action of running `Run Tests` now fails. 

When I go to the terminal, to my build directory, I can use `ctest` and all my tests run. Using the `Run Tests` command of `/usr/local/bin/ctest -j8 -C Debug -T test --output-on-failure` doesn't run the tests.

When I manually go into the terminal and run `/usr/local/bin/ctest -j8 -C Debug -T start --output-on-failure`, and then run `Run Tests` - everything works again.

**Comment by andreeis** [comment]
Thank you for opening this report. With a quick try on windows I wasn't able to reproduce this but I will explore ctest on linux and on more recent versions as well.

In the meantime, maybe we can notice something by looking at the logs in the output channel. Set the logging verbosity to debug "cmake.loggingLevel": "Debug" and run the test command again.

@leungyauming, when you see that DartConfiguration.tcl is missing, do you have "include (CTest)" in your CMakeLists.txt?
Please share us the output channel logs with the ctest command with and without -T, since you say that simply removing -T unblocks you.

@sureshjoshi, regarding running the ctest with "-T start" first. Once you do that, how do you get again into the state of "-T test" not running the tests? Can you share the terminal output when you run all these commands?

**Comment by sureshjoshi** [comment]
@andreeis Once I manually did the start, I think it continued to work using Run Tests (until I clear cache or something?)

I'll experiment more and report back. I also had an open ticket re: custom ctest commands that I want to test out too

**Comment by sureshjoshi** [comment]
Okay, so, I think I found out what might be happening. I think when jumping between ctest commands on the terminal and using the VS Code integration causes some weird behaviour. I wasn't able to come up with a full repro, but essentially, I do some commands from the terminal, and when I want to run everything I just use the VSCode button.

At some point, maybe some terminal settings corrupt the DartConfiguration.tcl (or some other files), and then the VSCode button shows that there are no tests to run. Wiping everything and re-doing configuration and build fixes this.

In the meantime, I've been maintaining two different build directories (one fully managed by VSCode, one fully managed by the terminal). Haven't run into any problems since. So, some command I'm running must be causing some shenanigans.

**Comment by andreeis** [comment]
Interesting. Some questions come to mind, not sure if they are all relevant but it doesn't hurt to ask.
Any "Ctrl+C" involved in your manual terminal operations?
While trying to reproduce, are you staying in the same terminal or you open new ones (there is the "+" button that some use, or the split button) and then you switch between them?
What kind of the terminal are you using, bash, cmd, powershell, etc....?

**Comment by sureshjoshi** [comment]
No manual terminations performed (rare that I even do this for my compilations ever, now that I think about it)

The terminal is the one embedded into VS Code (zsh, on my machine) - only ever 1 terminal at a time.

**Comment by andreeis** [comment]
We are still not able to reproduce this but we'll think of more experiments to try.
Is it handy for you to share with us your exact project, or a reduced form that reproduces the symptom?
