### ISSUE TITLE
Access "active folder"

### ISSUE THREAD

**Issue by guestieng** [microsoft/vscode-cmake-tools#1712]
Is there a way to get the active workspace folder (e.g. in a task)
or is it otherwise possible to implement this, i.e., via something like ${activeFolder}?

Moreover, a way to set the active folder ( like "cmake.setActiveFolder(\<name\>)" ) would be useful too.

**Comment by andreeis** [comment]
Can you try the variables ${workspaceFolder} for path or ${workspaceFolderBasename} for folder name? Might not be accurate in all the scenarios of tasks.json usage, let us know if they work for your case.

Regardless of how these variables above work for you, the extension can also expose a command that would return or set the activeFolder. Your tasks.json would access these with the command syntax: ${command:cmake.activeFolder} instead of the variable syntax ${activeFolder}. I opened work item https://github.com/microsoft/vscode-cmake-tools/issues/1715 for this.

**Comment by guestieng** [comment]
This is actually a little irritating: 
the variable ${workspaceFolder} always gives you the first(!) "path" entry in the "folders" array within the *.code-workspace file 
(variable ${workspaceFolderBasename} only gives you the piece after the last slash in the path path tail of ${workspaceFolder}).
Now, changing the first(!) "path" entry in the "folders" array does also change the "active folder"!
On the other hand, changing the "active Folder" (via menus) does not change the first(!) "path" entry or the order of entries in the "folders" (this is actually good, since I would'nt want the folders array be changed in such a way).

After all, yes, ${command:cmake.activeFolder}, would be helpful.
