### ISSUE TITLE
Broken debugging via CMake Tools on Windows 10

### ISSUE THREAD

**Issue by macareux** [microsoft/vscode-cmake-tools#1734]
### Brief Issue Summary

CMake Tools' debugging feature doesn't really work as intended. While the breakpoints sort of work, they don't properly execute. More specifically, in my case, I can't see anything once the `std::cout` line has been hit on either the integrated or external terminal. There is another, albeit minor, issue mentioned at the bottom. I also factory reset the PC just to see if it was an installation bug.

### Expected:

1. Place a breakpoint anywhere
2. Click the bug icon on the toolbar
3. Use the "Step Over" and other buttons to move between the lines of code, while executing that particular line of code

### Apparent Behavior:

1. Place a breakpoint anywhere
2. Click the bug icon on the toolbar
3. Nothing is displayed, either on the integrated or external terminal, when I step over

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.19.20122902-MSVC_2
- **VSCode Version**: 1.54.3 (User)
- **CMake Tools Extension Version**: 1.6.0
- **Compiler/Toolchain**: Visual C++ 2019 (from VS Community 2019)

#### main.cpp file:
```
#include <iostream>

int main()
{
    std::cout << "Hello World\n";

    return 0;
}
```

#### CMakeLists.txt file:
```
cmake_minimum_required(VERSION 3.10)

Project(Prototype)

add_executable(Prototype src/main.cpp)
```

#### c_cpp_properties.json file:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

An error also pops up when I reach the last line of code while stepping over some lines. It reads: 

> Unable to open 'exe_common.inl': Unable to read file 'd:\A01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl' (Error: Unable to resolve non-existing file 'd:\A01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl').

I have no idea why this shows up every time, but when I debug normally using the launch.json file, while I get the same error, the program seems to properly debug and I assume I can just ignore it.

**Comment by andreeis** [comment]
Thank you for opening this report.
Let me know if I understand correctly the third bullet in the `Apparent Behavior` section `Nothing is displayed, either on the integrated or external terminal, when I step over`: the problem is that you don't see output from code that is meant to print messages (printf, cout, etc...).
Your CMake project is successfully configured and you do have a launch target defined, otherwise no debugging would start at all.
Your source code is compiled for Debug variant, otherwise the breakpoints would not be hit and you wouldn't be able to step through and especially the same wouldn't work properly as you say it happens when you use F5 and launch.json.

Look in the "DEBUG CONSOLE" window (which is usually at the same level with "TERMINAL", "OUTPUT", etc...). That is where you should be able to see the output from "cout".

**Comment by macareux** [comment]
You are right that I don't see any output from `cout`, but I did use the debug variant for compiling and I also checked the Debug Console. Here's a screenshot for more context:
![Screenshot (1)](https://user-images.githubusercontent.com/75945056/112888517-580e6a80-90cc-11eb-825e-6ad4211fdbbe.png)
The 'Hello World' only appears after the debugging session has finished (i.e. not when the breakpoint is hit)

**Comment by andreeis** [comment]
I will follow up with the debugger team about the behavior of printing to output. In the meantime, you can try this workaround. I was able to reproduce how "cout" would print only at the end and then with this setting I was able to see each cout (I wrote several on different lines) after its own step-over.

   "cmake.debugConfig": {
      "externalConsole": true,
   },

VSCode will complain that "externalConsole" is deprecated and you need to use "console" but if you do then "cout" will still show the text at the very end. It's just a workaround so ignore the warning. We'll figure out what the real bug is and where it belongs.

**Comment by andreeis** [comment]
I found that even F5 with launch.json has the undesired behavior ("cout" prints at the very end) if "console" is "internalConsole").
CMake Tools debug command generates a brand new launch.json on the fly without mentioning "console" at all and probably the default for VSCode debugger is "internalConsole" which doesn't work and about which I'm following with the debugger team.

CMake Tools can make a quick fix to create this on the fly launch.json by specifying "console" as either of "integratedTerminal", "newExternalWindow" or "externalTerminal" which I see all three work (in launch.json or in CMake Tools).

But I see that even if CMake Tools doesn't generate the "console" attribute, you can still hook it up via "cmake.debugConfig", it will be seen and passed to the debugger. So the easiest workaround for you is to define:
"cmake.debugConfig": {
"console": "newExternalWindow",  <== or "externalTerminal" or "integratedTerminal" (I checked all 3 and they work from CMake Tools debug as well, not only from F5/launch.json)
}
Disregard my previous reply with "cmake.debugConfig.externalConsole" which is deprecated. It was true that if set to true it would also be a workaround (which I found accidentally) but since I was able to confirm what values to set "cmake.debugConfig.console" to, then use the workaround in this reply.

**Comment by macareux** [comment]
Thanks for your suggestion!
I tried this workaround for myself and I think it works fine now.

Just before this gets closed, I mentioned another issue at the bottom of my post. I was just wondering if I could safely ignore that error.

**Comment by AlexDev2020** [comment]
@Macareux: Maybe it's the absence of << std :: endl? When you write a string to std :: cout, it is written to the stream buffer and not immediately dumped to the console buffer, and the presence of std :: endl will force the contents of the stream buffer to be dumped to the console.

**Comment by macareux** [comment]
I tried using std::endl and that seems to get rid of the error. Sorry for not responding in such a long time.
