### ISSUE TITLE
CMAKE_BUILD_TYPE never change when I switch the debug/release 

### ISSUE THREAD

**Issue by ActivePeter** [microsoft/vscode-cmake-tools#1811]
![image](https://user-images.githubusercontent.com/8100696/115998617-adca2a00-a61a-11eb-8988-b4ab6d56673b.png)
![image](https://user-images.githubusercontent.com/8100696/115998631-ba4e8280-a61a-11eb-9650-4d6449dc3fc5.png)
has always been release in cmakecache when I change the build varient
![image](https://user-images.githubusercontent.com/8100696/115998699-14e7de80-a61b-11eb-8a9f-7cb8b9a73f8f.png)

**Comment by andreeis** [comment]
Thank you for opening this report. "Visual Studio"s are multi-config generators and they don't have a CMAKE_BUILD_TYPE. I tried to reproduce on my side and immediately CMAKE_BUILD_TYPE disappears from my simple project CMake cache. I don't understand why you still have it.
Is the build variant change triggering a configure operation? If not, can you run configure manually and look again at what happens with CMAKE_BUILD_TYPE in the cache?
Also, I am not sure that "Visual Studio 15 Win64" generator name is correct. It needs to have a "2017" between "15" and "Win64". Maybe some failure happens because of this setting?

**Comment by ActivePeter** [comment]
Well, It doesn't matter to me whether the CMAKE_BUILD_TYPE is there or not, and I do have a vs2017. I hope to know is there a way to judge the debug/release mode in cmakelist.txt. I need this info to choose different .lib files with or without the suffix 'd' when compiling.

**Comment by ActivePeter** [comment]
The CMAKE_BUILD_TYPE is still there after I ran configure.

**Comment by ActivePeter** [comment]
![image](https://user-images.githubusercontent.com/8100696/116819416-96eb8080-aba2-11eb-861a-c724f011cb2f.png)
I have solved my problem, and that CMAKE_BUILD_TYPE is created by me,
![image](https://user-images.githubusercontent.com/8100696/116819454-c13d3e00-aba2-11eb-8299-88b296a50ce9.png)

**Comment by andreeis** [comment]
Good to hear that.
