### ISSUE TITLE
ignored CMAKE_TARGET_MESSAGES

### ISSUE THREAD

**Issue by alanlivio** [microsoft/vscode-cmake-tools#1822]
### Brief Issue Summary
In cmake command line, when I use the -DCMAKE_TARGET_MESSAGES=OFF the building log is shown only in one line.

However, when I use the same flag in settings (see below), the building log is shown in multiple lines.
I use the CMAKE_TARGET_MESSAGES flag.
```
  "cmake.configureArgs": [
    "-DCMAKE_TARGET_MESSAGES=OFF",
   ]
```

**Comment by andreeis** [comment]
Thank you for opening this issue. We will try to reproduce on our side and investigate. In the meantime, it would help to see what command line is generated by CMake Tools. If it doesn't contain the define, the bug is that we lost it somehow. If it contains the define, maybe it gets invalidated by another switch after it, ... 

So give us the command line (or the full "Debug" loggingLevel log) for the configure process.
And the command line that works, which you run manually in terminal.

Also, if the extension didn't lose the define and it is present in the command, if you run it in the terminal and write it exactly as the extension calculated it, what happens?

**Comment by alanlivio** [comment]
any news @andreeis ?

**Comment by gcampbell-msft** [comment]
@alanlivio Is this still affecting you? 

If so, could you provide a minimal repro or at least some screenshots of the issue so that I can better understand it? Thanks!
