### ISSUE TITLE
Remove the extra drop down for configurePresets

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vscode-cmake-tools#1945]
### Brief Issue Summary

1. the target selection thing is missing (not discussed here. see #1872)
2. Selecting 3 presets (config, build, test) takes a lot of status bar space

### Expected:

1. target should be shown (like in non-preset-mode) (not discussed here. see #1872)
2. they should be combined into one button

Suggestion:

`<TOOLS> Presets | [Target] | <GEAR> Build | <BUG> | <PLAY> | <FLASK> Run Ctest`

Note: `<FOO>` are Icons, `|` seprarate clickable stuff

Presets should run > Select configure preset, Select build preset and Select test preset at once, (current one should be preselected) and not show the names in statusbar.
[Target] should be used for build and launch target

I know, some of this can be configured via `cmake.statusbar.advanced`, but some can not.

Another bonus would be to check if there is a config, build and test preset with the same name. Then use those on selection
```
> Select Presets
> Chose configuration presets
> The same preset name exist for build and test. Use those (**Yes** No)
Yes -> exit
No ->
> Chose build preset
> Chose test preset
```

### Platform and Versions

- **Operating System**:  Windows
- **CMake Version**: 3.20.4
- **VSCode Version**: 1.57
- **CMake Tools Extension Version**: 1.7.2
- **Compiler/Toolchain**: irrelevant

**Comment by bobbrow** [comment]
For the first issue, there is more discussion here: #1872
We will use this issue to track the second request.

**Comment by TheJCAB** [comment]
I have to agree with the OP sentiment. When working with presets, status bar real estate is now very tight when working on a vertical monitor, even though three things still seem sorely missing from it (I'm looking at cmake-tools 1.7.3):

- Which installation of the compiler, whether Visual Studio or other, to use. Used to be sort-of the "kit". The target architecture portion of the "kit" is now selectable from the preset, thankfully, but the actual compiler toolset to use, when multiple versions are installed on the computer (I currently have 3 Visual Studios to choose from), doesn't belong in the presets file (it's a factor of the computer itself) and should still be separately selectable "on the side".
- Which target to build: #1872 
- Which target to run/debug with the C/C++ tools extension.

That's way too much on the status bar, but all of it deserves a UI. Perhaps having the option of a sidebar pane with all of this...

I hope we can regularize all of this soon. In the meantime, presets are fairly new, so some inconvenience is to be expected :-).

**Comment by esweet431** [comment]
Thank you for the feedback. 

> Which installation of the compiler, whether Visual Studio or other, to use. Used to be sort-of the "kit". The target architecture portion of the "kit" is now selectable from the preset, thankfully, but the actual compiler toolset to use, when multiple versions are installed on the computer (I currently have 3 Visual Studios to choose from), doesn't belong in the presets file (it's a factor of the computer itself) and should still be separately selectable "on the side".

Curious, why do you not want to encode the compiler toolset in a preset or user preset? This can be done with the `toolset` and `architecture` options.

**Comment by bobbrow** [comment]
@TheJCAB I agree that having this stuff in a sidebar panel is better than putting it in the status bar.  We have discussed adding an additional panel in the existing Project Outline view but haven't been able to put it ahead of other competing priorities yet.  In the meantime someone contributed the status bar settings which is a sort of mitigation, until we can get this into a milestone. We would certainly accept a PR if any enterprising devs out there have some spare cycles to help us out with.

**Comment by TheJCAB** [comment]
@esweet431:

> Thank you for the feedback.
> 
> Curious, why do you not want to encode the compiler toolset in a preset or user preset? This can be done with the `toolset` and `architecture` options.

That would bake the version of the compiler into the file, which ends up checked-in in the repo. That's... not what is desired. It'd be ok to specify, say, a minimum compiler version. That'd allow the GUI to warn the user that the build might fail, if they have an older compiler than the one needed by the project.

Downsides:
1- This would preclude switching compilers, say, to validate issues in a newer compiler preview. Yes, a developer could just modify the file in order to do this validation, and then be careful not to check in the change, but that's not a good engineering practice.
2- This would lock developers to using a particular version of the compiler, preventing regular upgrades. Compiler upgrades would need to be done by mandate, and all developers in the project would need to stay in sync.

The exact compiler toolset installed in a machine is not something that can, or should, be baked into a project. it's as unsavory as baking full paths, to give a different example. It's possible to develop a project this way, but it's... far from ideal.

@bobbrow:

"additional panel in the existing Project Outline view" - You mean in the Explorer, along with "Open Editors", "Workspace", "Outline" and so on? It feels to me that a brand new whole side-pane would be preferable. There's definitely enough UI to put there to warrant that, and it'd be one less level of indirection, so to speak.

In any case, thanx! Here is to hoping this can be done in the not-too-distant-future...

**Comment by esweet431** [comment]
> That would bake the version of the compiler into the file, which ends up checked-in in the repo. That's... not what is desired. 

You can use a [user preset](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) in `CMakeUserPresets.json`, which is not intended to be checked in and saves local developer builds. In this case, you can inherit from a Configure Preset in `CMakePresets.json` and only specify the toolset version (or other user-specific options) in `CMakeUserPresets.json`.

**Comment by tntfb** [comment]
Actually, I don't see a reason why the Active Configuration Preset should even be in the statusbar. The Build Preset already carries its selected configuration preset, as per the cmake-presets documentation:

>`configurePreset`
>
>An optional string specifying the name of a configure preset to associate with this build preset. **If configurePreset is not specified, it must be inherited from the inherits preset** (unless this preset is hidden). ...

That CMake Tools is forcing a redundant selection of a configuration preset before the Build or Test preset cab be selected should be marked as a bug. The Configuration preset **should be** removed from the statusbar and the actual configuration should follow the selected Build or Test preset automatically.

**Comment by bobbrow** [comment]
@tntfb I agree and we're debating solutions that won't end up confusing folks because we would end up needing to merge configure and build presets (in the event there are none) in a single selection.  Some of this feedback goes back to Kitware and we're working with them on solutions.  We're just not finished yet.  Thank you for your feedback.

**Comment by TheJCAB** [comment]
Hi! I'm wondering what the status of this debate is, since a few months have passed. Consider this a friendly ping with commentary.

@tntfb "I don't see a reason why the Active Configuration Preset should even be in the statusbar. The Build Preset already carries its selected configuration preset" - This is not always true. For instance, when you build using MSVC+Ninja, the configuration preset already has to carry pretty much all the information needed to build (which compiler, host architecture, target architecture, target configuration...) So duplicating that information by generating a new list of build presets is redundant. We, for one, (I work on Microsoft Time Travel Debugging technology) then chose to obviate the build presets entirely (which is allowed by CMake). The only available "build preset" offered by VSCode in this case is "[[default]]".

I do agree that offering a selection of both configure and build presets, when there are no build presets in the file, is not very user-friendly. Same if there's exactly one build preset for each config preset.

CMake does offer the option of multiple build presets targeting a single config preset. This is useful, I'm sure, with MSBuild projects, where a single config can be built for multiple target architectures. CMake's choice of requiring all combinations to be listed individually in the file is unfortunate (IMHO) but it does allow maximum flexibility, and I'm sure there are plenty of ways in which a presets file might fail to conform precisely to any of the basic forms I mentioned (no build presets, or 1-to-1 config to build presets, or 1-to-N config to build presets). In the end, I'm sure, simplicity wins, so the tools extension just offers all the choices instead of trying to get too clever.

There's one choice that the tools extension still doesn't offer, and that's the choice of which development toolset installation to use. I currently have 3 different installations of Visual Studio (for reasons) and the tools extension is not allowing me to choose which one it'll use. The presets file is not a good option, AFAIK, because different people working on the project (or different machines they use) might have different minor versions/updates installed and IIUC we'd need to specify the full version there. I thought there was already an issue opened about this but I can't seem to find it. Maybe I should create one.
