### ISSUE TITLE
Unable to determine what CMake generator to use

### ISSUE THREAD

**Issue by skanda1993** [microsoft/vscode-cmake-tools#2005]
### Brief Issue Summary

I get an error "Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found."

### Expected:

1. I have installed VSCode, CMake, CMake tool plugin, C/C++ plugin, GCC from MSYS2 and developed a small software in C++
2. Installation path for MSYS2 does not contain spaces, accents, symlinks etc (C:/msys2)
3. Added` C:\msys64\mingw64\bin` to Environment path variable and `C:\msys64\mingw64\bin\x86_64-w64-mingw32-gcc.exe` on the C/C++ Edit Configuration UI under the section compiler path
4. CMake kit automatically detects the compiler and lists it (GCC 10.3.0 x86_64-w64-mingw32)
```
  {
    "name": "GCC 10.3.0 x86_64-w64-mingw32",
    "visualStudio": "3ca258ef",
    "visualStudioArchitecture": "x86",
    "compilers": {
      "C": "C:\\msys64\\mingw64\\bin\\x86_64-w64-mingw32-gcc.exe",
      "CXX": "C:\\msys64\\mingw64\\bin\\x86_64-w64-mingw32-g++.exe"
    }
  },
```
5. When Build on the status bar is pressed, project is expected to build

### Apparent Behavior:

1. When Build on the status bar is pressed, project is not building and throwing an error

### CMake Tools Log

```
[main] Building folder: <PROJECT_NAME>
[proc] Executing command: C:\msys64\mingw64\bin\x86_64-w64-mingw32-gcc.exe -v
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Build failed: Unable to configure the project {}
```

### Developer Tools Log

```
[21/07/2021, 16:28:12] For C source files, IntelliSenseMode was changed from "windows-msvc-x64" to "windows-gcc-x64" based on compiler args and querying compilerPath: "C:\msys64\mingw64\bin\x86_64-w64-mingw32-gcc.exe"
[21/07/2021, 16:28:12] For C++ source files, IntelliSenseMode was changed from "windows-msvc-x64" to "windows-gcc-x64" based on compiler args and querying compilerPath: "C:\msys64\mingw64\bin\x86_64-w64-mingw32-gcc.exe"
```

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.21.0
- **VSCode Version**: 1.52
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: MSYS2 GCC 10.3.0

**Comment by andreeis** [comment]
@skanda1993, thank you for opening this report.
Can you share with us your user kits file (VSCode opens it if you run the command "CMake: Edit User-Local CMake Kits" from the palette)?
Also, what kit did you select before configuring your project?
Do you have any kit/generator relevant "cmake." settings in your project (.vscode/settings.json) or at user level?
It may help if you set "cmake.loggingLevel" to "Debug" in your .vscode/settings.json, then reopen and configure your project in VSCode and share with us the content of the "CMake/Build" output channel.

**Comment by rustedwizard** [comment]
I am having exactly same issue. Here is my setup detail

VSCode version: 1.59.0 (user setup)
Cmake tool version: 1.7.3

Steps I have take:

I am use quick start to try to setup a project use LLVM 12.0.1 I installed on my computer, and I got following output at CMake/Build Channel:

[main] Safe constructing new CMakeTools instance
[variant] Constructing VariantManager
[main] Constructing new CMakeTools instance
[main] Starting CMakeTools second-phase init
[variant] Loaded new set of variants
[main] CMakeTools instance initialization complete.
[kit] Reading kits file C:\Users\chens\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Successfully loaded 17 kits from C:\Users\chens\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Not reading non-existent kits file: c:\Users\chens\source\Code_Repos\Hello\.vscode\cmake-kits.json
[extension] [4025] cmake.quickStart started
[kitsController] Start selection of kits. Found 19 kits.
[kitsController] Opening kit selection QuickPick
[kitsController] User selected kit {"label":"Clang 12.0.1 x86_64-pc-windows-msvc","description":"Using compilers: C = C:\\Program Files\\LLVM\\bin\\clang.exe, CXX = C:\\Program Files\\LLVM\\bin\\clang++.exe","kit":{"name":"Clang 12.0.1 x86_64-pc-windows-msvc","compilers":{"C":"C:\\Program Files\\LLVM\\bin\\clang.exe","CXX":"C:\\Program Files\\LLVM\\bin\\clang++.exe"}}}
[main] Injecting new Kit into CMake driver
[main] Starting new CMake driver
[main] Starting CMake driver
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using kit
[kit] Testing Clang binary: C:\Program Files\LLVM\bin\clang.exe
[proc] Executing command: "C:\Program Files\LLVM\bin\clang.exe" -v
[kit] Detected Clang compiler: C:\Program Files\LLVM\bin\clang.exe
[driver] CMakeDriver Kit set to Clang 12.0.1 x86_64-pc-windows-msvc
[driver] Trying to detect generator supported by system
[driver] Command version test return code -1
[driver] Command version test return code -1
[driver] Command version test return code -1
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[extension] [4025] cmake.quickStart finished (returned -1)


**Please note that this only happens when I selecting LLVM 12 I installed separately, if I choose LLVM toolset comes with Visual Studio or any MSVC toolset, I would not get this error.**

Also for you information following is content of  cmake-tools-kits.json:

[
  {
    "name": "Clang 11.0.0 (GNU CLI) (Visual Studio Professional 2019 Release - amd64)",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "amd64",
    "compilers": {
      "C": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\Llvm\\x64\\bin\\clang.exe",
      "CXX": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\Llvm\\x64\\bin\\clang.exe"
    }
  },
  {
    "name": "Clang 11.0.0 (GNU CLI) (Visual Studio Professional 2019 Release - x86)",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "x86",
    "compilers": {
      "C": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\Llvm\\bin\\clang.exe",
      "CXX": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\Llvm\\bin\\clang.exe"
    }
  },
  {
    "name": "Clang 11.0.0 (MSVC CLI) (Visual Studio Professional 2019 Release - amd64)",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "amd64",
    "compilers": {
      "C": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\Llvm\\x64\\bin\\clang-cl.exe",
      "CXX": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\Llvm\\x64\\bin\\clang-cl.exe"
    }
  },
  {
    "name": "Clang 11.0.0 (MSVC CLI) (Visual Studio Professional 2019 Release - x86)",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "x86",
    "compilers": {
      "C": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\Llvm\\bin\\clang-cl.exe",
      "CXX": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\Llvm\\bin\\clang-cl.exe"
    }
  },
  {
    "name": "Clang 12.0.1 x86_64-pc-windows-msvc",
    "compilers": {
      "C": "C:\\Program Files\\LLVM\\bin\\clang.exe",
      "CXX": "C:\\Program Files\\LLVM\\bin\\clang++.exe"
    }
  },
  {
    "name": "Visual Studio Professional 2019 Release - amd64",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "x64",
      "toolset": "host=x64"
    }
  },
  {
    "name": "Visual Studio Professional 2019 Release - amd64_arm",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "arm",
      "toolset": "host=x64"
    }
  },
  {
    "name": "Visual Studio Professional 2019 Release - amd64_arm64",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "arm64",
      "toolset": "host=x64"
    }
  },
  {
    "name": "Visual Studio Professional 2019 Release - amd64_x86",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "win32",
      "toolset": "host=x64"
    }
  },
  {
    "name": "Visual Studio Professional 2019 Release - x86",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "win32",
      "toolset": "host=x86"
    }
  },
  {
    "name": "Visual Studio Professional 2019 Release - x86_amd64",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "x64",
      "toolset": "host=x86"
    }
  },
  {
    "name": "Visual Studio Professional 2019 Release - x86_arm",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "arm",
      "toolset": "host=x86"
    }
  },
  {
    "name": "Visual Studio Professional 2019 Release - x86_arm64",
    "visualStudio": "4d8bfc75",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "arm64",
      "toolset": "host=x86"
    }
  },
  {
    "name": "VisualStudio.14.0 - amd64",
    "visualStudio": "VisualStudio.14.0",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 14 2015",
      "platform": "x64"
    }
  },
  {
    "name": "VisualStudio.14.0 - amd64_x86",
    "visualStudio": "VisualStudio.14.0",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 14 2015",
      "platform": "win32"
    }
  },
  {
    "name": "VisualStudio.14.0 - x86",
    "visualStudio": "VisualStudio.14.0",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Visual Studio 14 2015",
      "platform": "win32"
    }
  },
  {
    "name": "VisualStudio.14.0 - x86_amd64",
    "visualStudio": "VisualStudio.14.0",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Visual Studio 14 2015",
      "platform": "x64"
    }
  }
]

**Comment by rustedwizard** [comment]
Just add to previous comment, the issue can be work around if I add following setting to VSCode:

`"cmake.preferredGenerators": ["Visual Studio 16 2019", "Ninja"]`
