### ISSUE TITLE
Uknown language: ASM 

### ISSUE THREAD

**Issue by Hadatko** [microsoft/vscode-cmake-tools#2044]
### Brief Issue Summary

Hi, i have same issue as described here #1428 but with ASM language. I am using cmake as configuration file. From documentation [Cmake language support](https://cmake.org/cmake/help/latest/command/enable_language.html) there can be more supported languages. But the warning is bothering me for ASM language. Could you ignore this warning same way as in CUDA case?

### Expected:

Ignore warning with unknown language ASM

### Apparent Behavior:

`[cpptools] Unknown language: ASM` when `ENABLE_LANGUAGE(ASM)`

### Platform and Versions

- **Operating System**: Kubuntu
- **CMake Version**:  3.18.4
- **VSCode Version**: 1.59.0
- **CMake Tools Extension Version**: 1.73
- **Compiler/Toolchain**: armgcc 10

**Comment by bobbrow** [comment]
It is not ignored for CUDA.  You'll get the same warning if you pass an unknown `std` flag for CUDA.  I wasn't aware that you would ever need to pass a `std` flag for ASM.  Can you help us understand the case so that we can do the right thing here?  (For context, the extension only shows this warning when the `std` flag is set with an unknown language)

**Comment by Hadatko** [comment]
@bobbrow Hello, i am using project generated by NXP company. I didn't realized that they may generate unused flags for assembler compiler. I created Jira for them so i can close this one. 
Maybe you can consider to ignore the case instead of printing warning. Or for printing this type of information user would need set something in config file.
