### ISSUE TITLE
Question: Avoid "Select a Kit" popup when project is preconfigured with existing cache

### ISSUE THREAD

**Issue by jpfeuffer** [microsoft/vscode-cmake-tools#2143]
Hi,

I just have a short question: Is it possible to avoid the "Select a Kit" popup when a project is preconfigured with existing cache?
I am using the cmake-tools in GitPod (online VS Code IDE) with the prebuild feature and my project is completely preconfigured when opening VS Code.
However the "Select a Kit" dialogue still occurs and if a user selects the wrong Kit everything reconfigures. Even if the correct Kit is chosen, the dialogue is simply annoying.
I assume it happens because as stated in this issue: https://github.com/microsoft/vscode-cmake-tools/issues/1637
the active Kit is not saved in the settings.json but in the workspace state (which I assume is not saved on GitPod or any other online IDE after reload).

Is there a way around this?
Thanks

**Comment by bobbrow** [comment]
Can you try selecting the `[Unspecified]` Kit?  It's supposed to do what you are asking and avoid reconfiguring everything.

![image](https://user-images.githubusercontent.com/12818240/135488262-dd1ee9b4-48f8-4ce2-9d95-361d9a52269c.png)

**Comment by jpfeuffer** [comment]
Hi! Yes that indeed works, but is there a way to completely avoid the popup every time the workspace is loaded? It should be clear that a kit is already chosen when there is a pre-existing cache, no?

**Comment by bobbrow** [comment]
Possibly.  We don't always have enough context with just a CMakeCache.txt file.  If you want to use your cached configuration for IntelliSense, for example, we need more information from CMake and may have to "configure" again.  The presence of a cache may be enough for us to automatically select the `[Unspecified]` Kit, but complicates other commands like `Delete Cache and Reconfigure` which may require a Kit in order to work as expected.  I'm not saying it can't be done, but we'd need to think through all the scenarios before we make a change like this.

A way to get rid of that drop down in your projects today would be to start using `CMakePresets.json`.  ([More information](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/cmake-presets.md))

**Comment by jpfeuffer** [comment]
Thanks for your reply. I can see the problems coming with this. I will investigate the use of CMakePresets. It sounds like it could be exactly what we need anyway.
