### ISSUE TITLE
Windows VSCode, remote connect to Ubuntu linux, cmake error

### ISSUE THREAD

**Issue by fei4xu** [microsoft/vscode-cmake-tools#2218]
### Brief Issue Summary

I'm using VSCode on Windows, and use SSH remote connect to a Ubuntu based linux device.

VSCode can run on both Windows and Ubuntu locally with cmake, make debug.

When using remote connect, cmake can't run correctly.

### CMake Tools Diagnostics

```
{
  "os": "linux",
  "vscodeVersion": "1.61.2",
  "cmtVersion": "1.9.1",
  "configurations": [
    {
      "folder": "some.git",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}

```

### CMake/Build output

```
[proc] Executing command: /usr/bin/gcc-7 -v
[cms-client] Configuring using the "Visual Studio 15 2017 Win64" CMake generator with platform "undefined" and toolset "v140"
```
I'm curious why remote Kit is gcc-7 but cmake insist to generate "Visual Studio" toolset?

**Comment by andreeis** [comment]
@fei4xu, many things don't have expected values in the log that you shared. Is your project configured? Search for "cmake.configureOnOpen" set to false in your project or at user level. Also to make sure the configure step is at least attempted, run the "CMake: Configure" command from the palette. A log (from the output channel) of that configure action would also be helpful, plus the "CMake Diagnostics" that you already shared but ran again after you make sure the project is configured.

The VS part is due to some stale cache, so maybe even better, run the clean configure command instead of the simple configure: "CMake: Delete cache and reconfigure".

**Comment by fei4xu** [comment]
I opened the cmake settings (@ext:ms-vscode.cmake-tools) and reset this setting:

>Cmake: Generator
The CMake generator to use.

Now I can use cmake to configure/make my remote project.

**Comment by andreeis** [comment]
@fei4xu, glad that you got unblocked and you can continue to use the extension.
