### ISSUE TITLE
Ninja not able to build single-threaded starting with 1.9.1

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-cmake-tools#2222]
The fix for https://github.com/microsoft/vscode-cmake-tools/issues/1958 was meant for msbuild only, not as a general rule to skip over "-j" when parallelJobs is set to 1. This breaks ninja which cannot build single-threaded with CMT extension anymore.

**Comment by mark-ulrich** [comment]
This was my fear when submitting the PR. So what is the best solution? Is it to add a new configuration option? I considered this when creating the fix, but I was/am not familiar enough with the codebase to do so. I would be happy to work on this if no one else is working on it at the moment.

**Comment by bobbrow** [comment]
@mark-ulrich If you are willing to help out with this, we would appreciate it.

**Comment by bobbrow** [comment]
The fix for this issue is available in 1.10 "pre-release".  You can help us validate it by:
1. Opening the extensions panel in VS Code
2. Selecting the CMake Tools extension
3. Clicking the "Switch to Pre-release Version" button

![image](https://user-images.githubusercontent.com/12818240/156218538-7bce4a1f-4fc9-43cc-afb0-7f423aa5980e.png)
