### ISSUE TITLE
debugTarget failed when debug_config.environment not present.

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cmake-tools#2237]
debug_config.environment = debug_config.environment ? debug_config.environment.concat(util.makeDebuggerEnvironmentVars(configure_preset_environment)) : [];

means when debug_config have no environment  then  we can not debugging at all
even thout preset or toolkist are already configured it properly

**Comment by bobbrow** [comment]
The fix for this issue is available in 1.10 "pre-release".  You can help us validate it by:
1. Opening the extensions panel in VS Code
2. Selecting the CMake Tools extension
3. Clicking the "Switch to Pre-release Version" button

![image](https://user-images.githubusercontent.com/12818240/156218538-7bce4a1f-4fc9-43cc-afb0-7f423aa5980e.png)
