### ISSUE TITLE
CMake kit for MSVC 14.29 with VS2022

### ISSUE THREAD

**Issue by mpusz** [microsoft/vscode-cmake-tools#2245]
### Brief Issue Summary

Even though I have both MSVC 14.30.30705 and 14.29.30133 toolsets installed in VS2022 (both work correctly in VS2022), VSCode CMake extension does not detect the old VS2019 kit. The only one detected is the native one from VS2022.

When I edit the JSON file manually and try to add it manually it gets deleted when I try to select it via VSCode kit selection popup ("Scanning for kits..." appears and updates the file removing my changes).

**Comment by bobbrow** [comment]
Hmm... It shouldn't be automatically re-scanning. The only reason I could think of that it would be re-scanning is if there was an error in the JSON syntax.  You can also add a `cmake-kits.json` in the `.vscode` folder to augment the list of auto-discovered Kits ([reference](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/kits.md#project-kits)) and you don't have to worry about a rescan writing into that file ever.

Another option is to use [CMakePresets.json](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-presets.md) to configure your project instead of Kits/Variants.

These are all obviously workarounds to the bigger issue which is that we don't currently auto-generate Kits with downlevel toolsets.  We are tracking that issue with #694.

**Comment by mpusz** [comment]
Thanks for your response!
I tried to provide `cmake-kits.json` with the following contents:

```
[
  {
    "name": "Visual Studio Professional 2022 Release - amd64 (v142)",
    "visualStudio": "68cdd606",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "x64",
      "toolset": "v142"
    }
  }
]
```

However, after selecting it in VSCode I still cannot force CMake to use a correct compiler version (19.29). I always get:

```
[cmake] -- The CXX compiler identification is MSVC 19.30.30705.0
```

**Comment by wat-usmdon** [comment]
This seems to work for me, but I also needed to set "cmake.cmakePath" in the Visual Studio Code settings to the Visual Studio 2022 CMake and reload the window, otherwise Visual Studio Code would find and use the 2019 CMake instead, which doesn't have the Visual Studio 17 2022 generator.

```json
[
  {
    "name": "Visual Studio Enterprise 2022 Release - amd64 (v142)",
    "visualStudio": "555bf8bb",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 17 2022",
      "platform": "x64",
      "toolset": "v142"
    }
  }
]
```
