### ISSUE TITLE
Variable ${fileDirname} not resolved

### ISSUE THREAD

**Issue by albertopasqualetto** [microsoft/vscode-cmake-tools#2255]
### Brief Issue Summary

Why ${fileDirname} resolving is not enabled in cmake.sourceDirectory and cmake.buildDirectory?
I saw this (#869) Issue that led to the enable of a variable.

I think that it will be really useful.. in my setup I have a workspace with many folders inside and each folder is a different small school project, but I still need the bigger workspace because it gives me all my setup and settings and also it is my git "root" folder.

**Comment by bobbrow** [comment]
We don't support ${fileDirname} for those settings because it's not stable.  It can change whenever you open a new file.  We do support multi-root workspaces though and you could create a workspace that opens your folders. In that case I would think you could specify those settings at the Workspace level and they'd apply the same across all folders (assuming the folders are set up in a similar way).  I would even think that the default values might be sufficient and you wouldn't have to change them at all.

**Comment by albertopasqualetto** [comment]
Thanks, I resolved my problem with your suggestion.
