### ISSUE TITLE
Build progress popup prevents and delays information from showing inside the Output view

### ISSUE THREAD

**Issue by tntfb** [microsoft/vscode-cmake-tools#2337]
### Brief Issue Summary

When I start a build (via F7 or the command palette) in a VSCode CMake-tools project, there is a build progress dialog popping up in the lower right corner of the IDE window. This is something new, which wasn't there before. I have no way to confirm it, but I suspect it is this pop-up, which delays the normal CMake build information from showing up in the output view. Instead of the files being shown one by one as they are compiled, the Output view remains blank for a long time, then all of a sudden the output shows file number 200+ being built. This has the side effect of hiding any warnings during compilation of previous files being hidden.

I looked at the VSCode settings and also searched the internet, but there doesn't seem to be a way to turn of this annoying progress pop-up. I would rather have only the Output view showing the cmake/ninja/gmake output, rather than this useless progress bar.

For demonstration of the issue I did a short screen capture which clearly illustrates the shortcoming of the progress dialog.

https://user-images.githubusercontent.com/43143191/150661038-8e90e1e8-f45a-410d-8739-b2e1c371dd29.mp4

### CMake Tools Diagnostics
```json
{
  "os": "linux",
  "vscodeVersion": "1.63.2",
  "cmtVersion": "1.9.2",
  "configurations": [
    {
      "folder": "/home/foo/bar/baz/firmware/fw_smartblock_f4",
      "cmakeVersion": "3.22.1",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {
        "C": "/opt/arm-gcc/9.3.1/bin/arm-none-eabi-gcc",
        "CXX": "/opt/arm-gcc/9.3.1/bin/arm-none-eabi-g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 10,
    "executablesCount": 1,
    "librariesCount": 8,
    "targets": [
      {
        "name": "programmable",
        "type": "UTILITY"
      },
      {
        "name": "stm32f4xx",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "stm32f4hal",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "segger_rtt",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "freertos",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "usbhost",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "fatfs",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "stemwin",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "lwip",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "smartblock.elf",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

**Comment by tntfb** [comment]
Double-clicking the bell icon below the pop-up does nothing for the output view, it only minimizes the pop-up.

I also disagree with the statement that my system is fast enough to compile 200 files fast enough, which is the reason the output view does not update. You can clearly see in the video above, that about 11 seconds pass between starting the compilation process and updating the output view - in computer time this is an eternity.

**Comment by amurzeau** [comment]
Hi, I get this too, even when the output rate is slow, the output seems buffered.

After analysis and using tail on the 7-CMakeBuild.log file, I found that:

- The `7-CMakeBuild.log` file is updated as soon as the build output logs, so CMake extensions seems to not delay anything here
- The VSCode main process [poll that file for changes](https://github.com/microsoft/vscode/blob/648845d8692b5204254201b580f296cef9890abd/src/vs/workbench/contrib/output/common/outputChannelModel.ts#L68) to detect when to update the `CMake Build` output pane, with a `ThrottledDelayer` and a delay of 500ms.
- When there are changes, onDidContentChange event is triggered and [called](https://github.com/microsoft/vscode/blob/648845d8692b5204254201b580f296cef9890abd/src/vs/workbench/contrib/output/common/outputChannelModel.ts#L296), which cause [appendContent](https://github.com/microsoft/vscode/blob/648845d8692b5204254201b580f296cef9890abd/src/vs/workbench/contrib/output/common/outputChannelModel.ts#L210) to be called.
- `appendContent` will also use an `ThrottledDelayer` with a delay of 200ms.

But I'm not sure it's related to ThrottledDelayer.
When building using a single thread (out of 12) so Code.exe has enough CPU power left, I still get small hic-hups ("hangs" for around 2s instead of 500ms).
When using a script to happen lines to the 7-CMakeBuild.log manually (without any build running), VSCode displays the new lines from the file in the output pane with a perfectly regular rate of 500ms per update.

I'm wondering if VSCode could be busy doing something else, but the main Code process is not using CPU at all ... (not even one core).
