### ISSUE TITLE
Question\Request has multiplie CMake root directories.

### ISSUE THREAD

**Issue by AlmiAlmo** [microsoft/vscode-cmake-tools#2350]
Hello, i have project, what build for a specific compiler (XC8 pic).
But tests a building for win32.

To build app for production, i need to specify CMAKE_TOOLCHAIN_FILE at very start of root CMakeLists.txt
if im dont do this - CMake ignores next toolchain definitions and auto-pick system compiler.
So i cant(dont know) how to add both targets in one root CMake file.

VS Code extension want only one root. Can i workaround this somehow?

**Comment by bobbrow** [comment]
If you open two folders in a workspace, we should work with multiple roots.  I'm sure I understand what exactly you're trying to do that doesn't work though, so if opening both folders doesn't solve your problem, could you please help me understand your project structure better?

**Comment by bobbrow** [comment]
When you configure in the terminal, do you run cmake on the /Root/CMakeLists.txt?  If the problem is that you need to use a toolchain to configure from the root, we do support that.  You can specify it one of 3 ways:
1. Add `"CMAKE_TOOLCHAIN_FILE": "/path/to/toolchain.cmake"` to the `cmake.configureSettings` setting.
2. [Create a project Kit](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/kits.md) and specify the toolchain in the Kit.
3. Use [CMakeSettings.json](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-presets.md) and specify the `CMAKE_TOOLCHAIN_FILE` in the `cacheVariables` section of your `configurePresets`.

If that's not how you configure your project, you can add folders to your workspace by going to the `File` menu and selecting `Add folder to workspace...`.  Then you can configure each folder separately.
