### ISSUE TITLE
CMakeUserPresets.json version not detected without CMakePresets.json

### ISSUE THREAD

**Issue by nmm0** [microsoft/vscode-cmake-tools#2469]
### Brief Issue Summary

My project doesn't use `CMakePresets.json`, but I want to use a `CMakeUserPresets.json` (which is typically gitignored). I am using `toolchainFile`, a v3 feature and I have the version set to 3 in `CMakeUserPresets.json`. However the CMake tools report that `toolchainFile` is not supported in v2. After adding an almost empty `CMakePresets.json` with version set to 3, no errors are generated. I'm using the latest pre-release (v1.11.2). It seems like the tools only obtain version from `CMakePresets.json` and not `CMakeUserPresets.json`.

**Comment by bobbrow** [comment]
Thank you for reporting this.  Yes, indeed, the code currently looks at the version in the CMakePresets.json file instead of the version of the file from which the preset was parsed.  The code unfortunately wasn't written to track the version with the preset itself.  We'll need to make some changes to the way this works.

**Comment by chausner** [comment]
This should be fixed now that #2544 has been merged.

**Comment by bobbrow** [comment]
This feature is available in version 1.12.3 (pre-release). Thank you @chausner for submitting the PR!
