### ISSUE TITLE
Can't install pre-release version 1.11.10

### ISSUE THREAD

**Issue by hanjin-kim** [microsoft/vscode-cmake-tools#2504]
### Brief Issue Summary

related issue  #2442

Working via SSH remote env : From WIn10 to Linux. 
Tried to use the 1.11.10 pre-release version to solve the BASH_FUNC_* related problem.
Installation failed with error message:
 Can't install pre-release version of 'ms-vscode.cmake-tools' extension because it is not compatible with the current version of Visual Studio Code (version 1.66.2)

BTW, I also tried to unset the BASH_FUNC_* from my .bashrc but it does not seem applied when debug.

**Comment by hanjin-kim** [comment]
FYI, BASH_FUNC_* are introduced after the ShellShock and an issue related to them were also reported to vscode very long time ago, https://github.com/microsoft/vscode/issues/3928

**Comment by hanjin-kim** [comment]
Install 1.11.10 succeeded with VSIX but found the problem with BASH_FUNC_MODULE is not solved..

**Comment by bobbrow** [comment]
If you are having installation issues, could you please open an issue with the VS Code team?  Our extension is compatible with 1.66.2 and I have it installed.  The minimum version requirement is 1.63.0.

If you still are seeing a problem with the environment variable, please enable logging as described here: https://github.com/microsoft/vscode-cmake-tools/issues/2442#issuecomment-1075399543

Then share the contents of the output window with us so we can see what the problem is for you.  Thanks!
