### ISSUE TITLE
How do I import an existing cmake build directory?

### ISSUE THREAD

**Issue by BrentHuang** [microsoft/vscode-cmake-tools#2807]
### Brief Issue Summary

The first step is to select the main CMakeLists.txt file of the project:
![image](https://user-images.githubusercontent.com/2862064/196570246-f872db9b-208c-4024-949c-7280143e294a.png)

Second, import the existing cmake build directory: 
![image](https://user-images.githubusercontent.com/2862064/196570048-c8a9a5fc-6f73-44d7-8f96-b2a567359076.png)

How to do this like qtcreator? Because when I execute cmake from the command line, I pass in a lot of parameters that are already generated in the build directory, and I don't want to manually specify them again in vscode.

**Comment by bobbrow** [comment]
There is a setting you can use to tell us not to try to rerun configure for you: `cmake.skipConfigureIfCachePresent`.  It will be your responsibility to make sure the project is correctly configured.  I believe you only need to tell us where the cache is via the `cmake.buildDirectory` setting so that we use it.

**Comment by ihnorton** [comment]
FWIW, [this](https://github.com/microsoft/vscode-cmake-tools/issues/2807#issuecomment-1287494688) appears to almost work as stated, _however_ CMakeTools does not respect the existing generator in the cache -- it tries to build with ninja (by default) regardless of the existing generator. Changing the preferred generator order to match my existing cache fixed it for me, but this seems to be gotcha.
