### ISSUE TITLE
Warnings disappear from problems tab when rerunning a target

### ISSUE THREAD

**Issue by quyykk** [microsoft/vscode-cmake-tools#2902]
### Brief Issue Summary

Rerunning a target after a successful build clears the problems tab from any warnings that were generated during the build.

1. Add a new unused variable to your project
2. Run the program by clicking the > arrow in the task bar ("Launch the selected target in the terminal window").
3. Notice that the unused variable warning appears in the problems tab
4. Run the program again by clicking the > arrow.
5. Notice that the unused variable warning is gone

This is also the case when just clicking "Build" repeatedly.

**Comment by bobbrow** [comment]
This is probably the expected behavior.  If you do not tell the compiler to treat warnings as errors, you will not be notified of the warnings during the next round of compilation unless you also made changes to the file with the warnings.  This is because the build system tries to optimize the build by only rebuilding source files that have changed.

**Comment by bobbrow** [comment]
(though perhaps what you're reporting is that maybe the extension should track whether any changes have been made in files and not ask cmake to rebuild if you click the play button two times in a row without doing anything else?)

**Comment by quyykk** [comment]
> (though perhaps what you're reporting is that maybe the extension should track whether any changes have been made in files and not ask cmake to rebuild if you click the play button two times in a row without doing anything else?)

Kinda, but not really. I would like warnings in files that haven't be recompiled to stay. because since the file wasn't recompiled the warnings are still there. Your solution would not work if I modify a different file for example.

**Comment by bobbrow** [comment]
> Kinda, but not really. I would like warnings in files that haven't be recompiled to stay. because since the file wasn't recompiled the warnings are still there. Your solution would not work if I modify a different file for example.

Correct, it would not work if a different file was edited unless we tracked modifications at the file level. But we won't do something like that because we'd have to maintain the full build graph to track dependencies and essentially implement a sort of build system ourselves.  So is there anything you think we can do to make this scenario better?  A workaround that you can use today is to reissue the command in the terminal.  This will rerun the program without starting a build.

**Comment by quyykk** [comment]
> So is there anything you think we can do to make this scenario better?

Then your suggestion is a good idea then, because it would be a step in the right direction. Thanks!

**Comment by bobbrow** [comment]
We will mark this as resolved then.  I don't have any other ideas to preserve the warnings besides never clearing them (which I'm sure many people will not appreciate).
