### ISSUE TITLE
The tasks' targets are not resolved when "cmake.buildTask" is used

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cmake-tools#2970]
### Brief Issue Summary

When searching for matching tasks, we try to compare the targets.
https://github.com/microsoft/vscode-cmake-tools/blob/b6668bdb18d290216fe6be703eb1ba67fceaafa9/src/cmakeTaskProvider.ts#L223-L232

However, we don't resolve the targets such as `"${command:cmake.buildTargetName}"` before comparison.

**Comment by elahehrashedi** [comment]
[piomis](https://github.com/piomis) since you have contributed to this code before, do you think you can take a look at this issue? Thank you.

**Comment by piomis** [comment]
@elahehrashedi  I will take a look.

**Comment by eseiler** [comment]
Seems to be related to #2959

As for an example, the following just runs CMake as a task.
`tasks.json`:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build ",
            "command": "/usr/bin/bash",
            "args": ["-c", "${command:cmake.tasksBuildCommand}"],
            "type": "shell",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "clear": true,
                "panel": "dedicated",
                "echo": true,
                "showReuseMessage" : true
            },
            "options": {
                "cwd": "${command:cmake.buildDirectory}"
            },
            "problemMatcher": "$gcc"
        }
    ]
}
```

I think you need to have `"cmake.buildTask": true` set.

With `v1.12.27`, this task was detected, but it is not any more with `v1.13.XX`.

Personally, I prefer using a task because:
* there is colored output
* tasks are run in the Terminal tab (instead of the Output tab)

But it's also handy when you need to do some things (via task's `dependsOn` config) before running cmake build or ctest.

**Comment by piomis** [comment]
This report is for sure not related to behaviour which you observe.
Like I wrote in #2959 - shell task behaviour was changed.
I proposed to keep #2959 to track discussion about tasks types.
