### ISSUE TITLE
Add a setting to disable test explorer integration

### ISSUE THREAD

**Issue by vakokako** [microsoft/vscode-cmake-tools#3145]
### Brief Issue Summary

We are using [C++ TestMate extension](https://github.com/matepek/vscode-catch2-test-adapter) for viewing and running tests in vscode. After the recent update of cmake tools, it takes over the test explorer window, overriding TestMate behaviour for refreshing, running, etc.

Could you introduce some settings that would disable test explorer integration?

**Comment by gcampbell-msft** [comment]
@vakokako Thanks for the feedback, we'll put this on our backlog for our next official release.

**Comment by xisui-MSFT** [comment]
@vakokako Can you explain this a little more with screenshots? The test explorer shouldn't be "taken over". If there are more than one extensions trying to add test explorers, the explorer should have multiple roots, each corresponding to an extension instead.

**Comment by rjra100** [comment]
We're using CMake Test Explorer until this feature matures a bit more (the [lack of parallel execution](https://github.com/microsoft/vscode-cmake-tools/issues/3091) is a blocker for us). For us at least, It does indeed give multiple roots, but it's mildly irritating to have all the tests listed twice, particularly since running them via CMake Tools takes so long.

For the moment we're working around it by providing a dummy ctest containing nothing but a bash script `echo {}` (i.e. print an empty json file); then set the `cmake.ctestPath` setting to `<path>/dummyctest`. That way the extension does produce a test root, but it doesn't contain anything or take any time to run.

**Comment by quyykk** [comment]
I'll go even further and say that the integration should be disabled by default. It is not mature enough and has regressions in my use cases too (see the issues I created).

**Comment by tsondergaard** [comment]
> @vakokako Can you explain this a little more with screenshots? The test explorer shouldn't be "taken over". If there are more than one extensions trying to add test explorers, the explorer should have multiple roots, each corresponding to an extension instead.

This is indeed the case. It is also possible to right-click the whole CTest and select "Hide tests". Despite this being possible it would be great to be able to ship a configuration that disables this integration completely as it can confuse developers that there are two ways to list the same tests with different capabilities.
