### ISSUE TITLE
A/B Experiment for CMake Status Bar Migration to the Side Panel

### ISSUE THREAD

**Issue by sinemakinci1** [microsoft/vscode-cmake-tools#3202]
### Brief Issue Summary

Hi there!

Our team is conducting an A/B experiment over the course of the next month for the CMake action items on the status bar by migrating them to the sidebar CMake extension, in attempt to collect data related to this clean-up of the UI. To access your CMake presets and build/debug actions if you are in the treatment, please navigate to the CMake Tools side bar. 
![f98c97e1-ed1b-4e97-823f-10511f3bd5b1](https://github.com/microsoft/vscode-cmake-tools/assets/99284450/6768fc39-eddc-428a-8819-04190275e034)
We are collecting metrics on which option is better for user's workflows, while taking into account UI consideration. Please leave any feedback you have on the experience below and if you could change anything about the design!

To opt out if you are receiving this treatment and no longer want to while we are running the experiment, please go to Settings and uncheck "Cmake: Use Project Status View". If you want to opt-into this treatment and give it a try, please check that option in settings.

**Comment by rminderhoud** [comment]
I was opted into this test group today and found it incredibly confusing. I was questioning what could have possibly happened to my environment that my normal build options are not appearing on the status bar. I dug through to check my extensions to see if anything changed and did not notice anything. Having some information available to me within VSCode that I was forceably subjected to this test would have been kind (maybe leaving a comment in the status bar context menu or SOMETHING.

![image](https://github.com/microsoft/vscode-cmake-tools/assets/1752584/1df82fd1-b08e-488f-8457-0780bd415005)

Now for direct feedback on the actual feature, I prefer the options to be present on the status bar and I would switch if that option was provided to me but it seems I am forced to use the old way (the recommended option in the top post is not available to me)

![image](https://github.com/microsoft/vscode-cmake-tools/assets/1752584/ca51ad07-34f5-4aa4-a8f6-633206b41d71)

I prefer to have it on the status bar since it is easily accessible and doesn't require a context switch away from what I am working on. For example if I have a Find & Search window open looking for references I can switch a build option without having to switch to a different panel. This is similar to Visual Studio where the build/configuration options are always available at the top of the window. To me having it in a separate panel that can lose focus is a regression in usability. Additionally, I often will trigger a build visually by clicking the build button rather than using a shortcut or a command. Maybe I'm a caveman but this is my preferred workflow. Finally, I will often have multiple text editors open and the panels completely hidden, I find it annoying to have to open and reflow my current view just to make some setting changes for my build.

Finally, in my panic to find what went wrong I actually did open this new panel and while it looked familiar I just assumed it was a parallel feature that was always there. To me it wastes a lot of screen real estate compared to the status bar way. I think for users who are aggressive with shortcuts and commands this won't be as disruptive but for us cavemen who like to click and point the change is quite jarring.

**Comment by sinemakinci1** [comment]
Hi @rminderhoud , thank you so much for your feedback and so sorry for the confusion we caused! We will definitely consider this workflow and input in the final design.

In the meantime, to opt out, you can navigate to the bottom left Gear icon and select "Settings"
<img width="179" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/99284450/cae3cbba-850b-43ed-88e2-4b75565fae20">
From there, you can search "UseProject" and under Cmake: Use Project Status View, you can uncheck the option to get your status bar icons back:
<img width="602" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/99284450/20bb6cae-017d-426c-99fb-029594a729dc">
Hope this helps un-block your workflow in the meantime!

**Comment by evg-trushkin** [comment]
Hi! 
First of all, thanks for a nice extension! 

I've a similar to @rminderhoud experience. The UI change was very confusing.

Regarding the feature:  
It seems that "Target" list in the status bar has got no direct equivalent in the new UI. For example, "install" target is disappeared, "all" target is not obvious to select, and some targets' names are changed in my case.

So it would be nice to add a target selector it the "Project status" part as is. Digging the tree in the "Project outline" is not always fun as well.

**Comment by pJunger** [comment]
I also found the change very confusing and I questioned my sanity because I though I somehow broke my CMake projects.

In general I don't need all elements in the status bar so often that I need them there.
But I use the build target selection (& build button) pretty often and I guess this varies from usecase to usecase.
Maybe have it more fine granular and let users decide which of those elements are valuable enough for them to be in the status bar?

**Comment by lichjian** [comment]
This sudden change makes me feel like the cmake extension has been compromised, and I will spend time searching for this issue. Personally, the new method is not intuitive for me, and when I use it, I also need to switch the buttons on the left sidebar. I still prefer to use it on the bottom status bar

**Comment by gatchamix** [comment]
noticed that my icons had vanished this morning and went through the process of reverting to the old behaviour.

As for the new UI design:
I feel it's significantly more steps to do something trivial, like changing the debug/launch target (click cmake tools sidebar -> scroll to debug/launch options in project status view -> hover the option -> click the edit button -> choose the target from the top bar) and now you don't have immediate view of the target (on the status bar) you're about to launch/debug via F5.
This is a massive regression honestly.

At the very least, the option to have both views working simultaneously should be given. I have no problem with the additional information being present in the cmake tools sidebar view, but removing the shortcuts from the bottom bar is a 100% no from me. I hope, at the very least, the option to keep the old behaviour remains.

**Comment by DubbeleJ** [comment]
Dear CMake tools team,

Good to see that the team is trying new things to improve the experience with the CMake tools for vscode. Like the people who have responded before me I was at first very confused and thought I had somehow broken my vscode installation.

For my feedback.
The new sidepane design does not work at all for my workflow. I use the tooling in the following way.

1. Select toolkit.
    I switch often between toolkits to develop locally on unit tests, or crossplatform to test on embedded targets.
    This is not affected as I use the ctrl+p command interface for this.
2. Configure.
    Same as point 1.
3. Build application.
    For this, I always use the controls in the status bar to quickly build the application, or whole project.
    The new layout does not contribute for this, I have to first navigate to the correct pane on the left hand side. Arriving there, I still have no clue how to build the project which is what I want to do. I have resorted to using the terminal + manual commands again to do building.

This said, I feel that the quick actions in the status bar should be kept in some form as I think more people will use the tooling in this way.

**Comment by snehara99** [comment]
Hi @DubbeleJ, in order to build there should be a button that appears to the side of the `build` item in the side bar when you hover over it. If you don't see that option, could you create an issue and post a screenshot of how the Project Status View (in the side bar) appears for you? Thanks!

**Comment by TheJCAB** [comment]
Besides the initial "what's going on here" shock, I have three observations:

1- There is no longer an UI way to select the CMake target to be built. You can still Ctrl+Shift+P for it, as you can for everything else, but... looks like an oversight looking for a quick fix.
2- The statusbar Advanced and Visibility settings say "Only applies when [Cmake: Use Project Status View](vscode-file://vscode-app/c:/Users/jcab/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) is set to false". I think that is a mistake (along with perfectly valid CMake command-line settings being purposefully ignored when using presets... hint, hint!) Even is the CMake side panel has all the options, it's be great if we could choose our own "frequent use" ones to remain visible and operable in the statusbar.
3- The UI as it is is awkward to use. Need to click the tiny "edit" icon in order to select a preset, instead of it being offered right there in the tree view. Or at least give me a sizeable button like we had in the status bar. The use of a tree view here feels... clumsy. Feels placeholder. I hope it is.

Suggestion: I love having a CMake-centric side panel. So put more good stuff in it! Not just what was on the limited-space statusbar: Buttons to delete cache, configure and build. A button to access CMake settings (like other extensions have). A button to provide feedback (a link to here). Stuff like that.

I hope this can evolve into something that delights. Definitely not there.

I also hope you can somehow make A/B experiments like this more discoverable (like a button in the status bar that reads "cmake stuff has moved", which opens the side panel when clicked) and perhaps more easily opt-outable, for instance a notification dialog saying something like "You've been selected to make CMake tools better... Ok? [Yes] [No]".

Not sure if it's related or not, but... there's also a project outline there that's... weird and awkward to use. Weird because it shows a long list of "utility" targets (named "Continuous", "Nightly"...) and I don't know what they are, and how they got there. Awkward because it shows the same directory tree of the workspace (filtered to directories that have targets in them), so it's... hard to find targets in there to operate on (at least in our project(s)). Anyway, this might be off-topic but... I thought I'd share.

**Comment by dlucas9** [comment]
I wasted hours trying to figure out why the buttons disappeared as compared to my other system.  Please don't make these kinds of changes without some sort of notification.... holy ... !!!!
