### ISSUE TITLE
cmake presets not overwriting conditions

### ISSUE THREAD

**Issue by Emiliskog** [microsoft/vscode-cmake-tools#3340]
### Brief Issue Summary

When using a base Preset with a condition like 
"condition": {
"type": "notEquals",
"lhs": "${hostSystemName}",
"rhs": "Windows"
}
for non windows builds and using the condition 
"condition": {
"type": "equals",
"lhs": "${hostSystemName}",
"rhs": "Windows"
}
on a preset that inherits the base one and is as used as a base for windows presets vscode/cmake tools does not let you access any presets on windows while visual studio and command line cmake both show all presets inheriting the second condition

**Comment by gcampbell-msft** [comment]
@Emiliskog This seems like it may be an issue in our resolving of CMakePresets, however, I won't know for sure until we reproduce and investigate. Marking the issue as such. 

In the meantime, would you be able to instead of trying to extend one base to create another base, could you simply create two separate base presets for Windows versus Linux?

**Comment by Emiliskog** [comment]
my temporary solution has been to have one base then extend that into one for windows and one for linux with the linux one essentially only being the conditionals so there is a workaround and thank you for looking into it
