### ISSUE TITLE
Compiler error messages report wrong file path on Windows

### ISSUE THREAD

**Issue by patrigg** [microsoft/vscode-cmake-tools#336]
### Brief Issue Summary
Compiler error messages link to wrong file paths when the workspace path includes upper case characters under Windows. When I select a compiler error from the Problems view, an already opened file is opened a second time but with a lower-case path. This completely messes up the respective file when the source code is reformated as vscode supposedly does not assume a single file to be opened twice.

### Expected:
Casing of the workspace path should be preserved by CMake Tools. So error messages will show the path with the correct case.

### Apparent Behavior:
The workspace path is converted to lower case when CMake is called.

The issue can be reproduced by the following steps
On Windows:
1. Copy a cmake project to a path containing upper case letters
2. Introduce a compiler error to a source file in the project
3. Ensure the respective source file is still open
3. Compile with CMAKE: Build
4. Click on the error message in the Problems view
5. The file is opened a second time in VSCode.

### CMake Tools Log

When the project is in the path: "C:\Code/UpperCaseIssue" cmake is called with a lower case path:
```
[vscode] Executing command: cmake --build c:/code/uppercaseissue/build --target all --config Debug -- -j 6
```

### Platform and Versions

- **Operating System**: Windows
- **VSCode Version**: 1.20.1
- **CMake Tools Extension Version**: 0.10.4
- **Compiler/Toolchain**: Visual C++ 2015

### Other Notes/Information
I guess the case should not be normalized, even on Windows operating systems (normalizePath in util.ts).

**Comment by bobbrow** [comment]
If you are building with VC++ 2015, the compiler is the culprit here.  I believe that most (if not all) VS projects turn on the /FC switch which results in full paths in the build output, but they are all lower-cased in the output.  Normally this shouldn't be a problem because the Windows file system is case insensitive, but VS Code treats these paths as unique.

So while some of the blame can be put on the compiler, this is actually a VS Code issue.  Issue https://github.com/microsoft/vscode/issues/12448 is where most of the discussion on this is happening.  I recommend you upvote that issue.
