### ISSUE TITLE
Should choose correct header candidate for `C_Cpp.default.configurationProvider`

### ISSUE THREAD

**Issue by loynoir** [microsoft/vscode-cmake-tools#3406]
### When

- I use

```json
"C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
```

- I remove a dependency from `vcpkg.json`.

### Expect

`ms-vscode.cpptools` jump to system header.

### Actual

`ms-vscode.cpptools` jump to removed vcpkg dependency header.

**Comment by gcampbell-msft** [comment]
@loynoir In order to investigate this issue, we'll need some more information as well as a repro sample project. 

Is the issue coming from not re-configuring or not-rebuilding after making those changes? What was the c_cpp configurationProvider before modifying that setting? 

If you could provide more information so that we can assist in this investigation, that would be great, thanks!
