### ISSUE TITLE
Do not show a Configure failed notification when configuring was canceled by the user.

### ISSUE THREAD

**Issue by teo-tsirpanis** [microsoft/vscode-cmake-tools#3472]
### Brief Issue Summary

When I cancel configuring my CMake project, the extension still shows at the bottom-right a notification that configure failed and prompts me to reconfigure with a debugger.

But since I cancelled the configure

**Comment by sinemakinci1** [comment]
related to #3343

**Comment by snehara99** [comment]
@teo-tsirpanis Thank you for creating this issue. Since this is a specific scenario of #3343, it would be helpful if you could comment your issue on that thread and like the original post to bring more visibility. I will close this as a duplicate so that interest doesn't get diluted between two issues (it helps us track better to keep only one).
