### ISSUE TITLE
cmake presets do not inherit PATH

### ISSUE THREAD

**Issue by huangqinjin** [microsoft/vscode-cmake-tools#3473]
### CMakePresets.json
```json
{
  "version": 3,
  "configurePresets": [
    {
      "name": "default",
      "environment": {
        "PATH": "C:\\msys64\\ucrt64\\bin;$penv{PATH}"
      }
    },
    {
      "name": "empty"
    },
    {
      "name": "custom",
      "inherits": [ "empty", "default" ]
    }
  ]
}
```

### CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.26)
message(STATUS "PATH=$ENV{PATH}")
project(tmp NONE)
```

Configure with `cmake --preset=custom` from cmd, the output `PATH` starts with `C:\msys64\ucrt64\bin`. But in VS Code, the output `PATH` doesn't include `C:\msys64\ucrt64\bin`.

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.84.2",
  "cmtVersion": "1.17.3",
  "configurations": [
    {
      "folder": "c:\\tmp",
      "cmakeVersion": "3.27.6",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [
      ""
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

**Comment by gcampbell-msft** [comment]
@huangqinjin Thanks for posting this issue. I've confirmed that this isn't a regression from our extensions point of view, but we definitely need to make sure it works correctly, triaging it appropriately.

**Comment by gcampbell-msft** [comment]
@huangqinjin I recently made a slightly different fix due to a regression. I've confirmed locally that my changes still fix the issue, but if you could confirm that would be great!

Could you download this file:
[cmake-tools.zip](https://github.com/microsoft/vscode-cmake-tools/files/14361639/cmake-tools.zip)
, change the extension to a .vsix. and install it manually in VS Code and confirm that it still fixes your issue? I locally tested and I believe it still fixes your issue, but please confirm.
