### ISSUE TITLE
CMake tools not honoring absolute path

### ISSUE THREAD

**Issue by wjk** [microsoft/vscode-cmake-tools#3475]
### Brief Issue Summary

[I have a project](https://github.com/wjk/ReactOS). When I configure it in VSCode, I get an error stating that the names of the C and C++ compiler binaries are not found in the system path. These binaries cannot be put in the path due to the fact that the OS launches VSCode for me, instead of my running the binary directly, so I have no way to influence its environment. However, these binaries’ absolute paths are located in the `CMakeCache.txt`, and are correct.  VSCode configures CMake just fine, but then it complains that it cannot find the compilers and as such all editor features are disabled. The build does not fail, as long as I only use the command line. What can I do about this?

### Additional Information

The log fields were too big for GitHub to handle, so I have attached them as files below.

[This is the CMake > Log Diagnostics output](https://github.com/microsoft/vscode-cmake-tools/files/13516259/cmake-diagnostics-log.txt).  
[This is what I find in the output window when running under debug logging](https://github.com/microsoft/vscode-cmake-tools/files/13516264/cmake-debug-log.txt).

**Comment by gcampbell-msft** [comment]
@wjk Thanks for notifying us of this. This definitely seems like a bug that we should investigate. 

Are you using this on Linux? Or is this possibly an Msys environment? Any more info about your environment may be helpful to us when we investigate.

**Comment by lukka** [comment]
@wjk thank you for reporting this issue! I have forked your project repository and added a `CMakePresets.json` (which is the recommended way to use CMake with), and I got IntelliSense working in the C/C++ files. Here my steps:
- using a Linux Ubuntu WSL2 Ubuntu 22.04.1 LTS (jammy).
- cloned the repository `git@github.com:lukka/ReactOS.git` .
- Running: `sudo add-apt-repository ppa:reactos/rosbe-unix`  and `sudo apt install rosbe-unix` to install the RosBE environment.
- Launching the build environment with: `/usr/RosBE/RosBE.sh` .
- From the RosBE shell (and its environment), I started up `code` and opened the folder of the repository.
- Using the `CMakePresets.json` I could configure and build the source code and have the IntelliSense working, here the output of configure and build: [configure-and-build.txt](https://github.com/microsoft/vscode-cmake-tools/files/13923032/configure-and-build.txt)

Let us know if leveraging a CMakePresets.json is a viable way for you as well and also if this is going to help you working on your codebase. If you are experiencing any problem just reach out to me. And if CMakePresets.json is not not possible to be used for you, we'd need to repro the problem with the kit files on your system at `/Users/williamkent/.local/share/CMakeTools/cmake-tools-kits.json`.
Please keep the feedback coming and thank you for the detailed report!

**Comment by wjk** [comment]
Unfortunately, your steps don’t work for me at all, because I am using macOS and not Linux or Windows. I have no way to influence the PATH or environment of the VSCode process.

**Comment by lukka** [comment]
@wjk given that `macOS` and `Linux` are both unix-like OSes, I thought it could be possible to follow the steps from "Launching the build environment with `/usr/RosBE/RosBE.sh`" (included) onward. I hope it is possible for you to install the RosBE environment on macOS using the RosBE Unix archive (provided [here](https://reactos.org/wiki/Build_Environment)) .

An additional thought: do you think it would help if you could describe your steps as I've done so that I can try to repro this issue on macOS? I am looking forward to see how you install RosBE, how you spawn the build environment, and how you start vscode.

**Comment by wjk** [comment]
I have very much installed the RosBE tools, but it does not matter. I can run `RosBE.sh` as much as I want, but if I launch VSCode, it will be forked from a system process that I have no way to touch. I cannot put any environment variables into the VSCode process.

**Comment by lukka** [comment]
@wjk please note that in the steps I described in [this message](https://github.com/microsoft/vscode-cmake-tools/issues/3475#issuecomment-1889831060), VS Code is being launched by the RosBE environment prompt, hence it runs inside the build environment: this is accomplished by launching from a terminal the ReactOS Build Environment (in my case launching command `/usr/RosBE/RosBE.sh`, where it was installed), and then from the same terminal at the RosBE prompt I launched `code`, which is the executable launching up VS Code. At that point, VS Code is running inside the RosBE environment, and all the environment variables are the ones defined by RosBE. This is leveraging the knowledge that a process inherits the initial environment (e.g., the environment variables) from the process it was spawn from.

Is this a viable approach for you? Let us know!

**Comment by wjk** [comment]
It works!

**Comment by lukka** [comment]
@wjk thank you for reporting back! Let us know if you encounter other problems or have any suggestion!

Note: The following feature described at https://github.com/microsoft/vscode/issues/152806 was proposed time ago and it would help supporting scenario similar to the `RosBE` where the build needs to run in a specially crafted environment. Since that feature has not moved forward from its initial proposal, the only solution nowadays is to start the VS Code process from the required environment as suggested in this case.
