### ISSUE TITLE
Investigate and track colorized CMake/Build output API dependencies

### ISSUE THREAD

**Issue by sinemakinci1** [microsoft/vscode-cmake-tools#3683]
### Brief Issue Summary

Investigation tracking item for #478 to ensure API dependencies are tracked and completed where relevant

**Comment by gcampbell-msft** [comment]
Some locations that will help investigate: https://github.com/microsoft/vscode/issues/145234#issuecomment-2037613152, https://github.com/microsoft/vscode/pull/209548

**Comment by gcampbell-msft** [comment]
Update on the API: https://github.com/microsoft/vscode/issues/145234#issuecomment-2045374547

**Comment by gcampbell-msft** [comment]
Adding reference #2783

**Comment by gcampbell-msft** [comment]
Overall, in response to this comment and adding more context: https://github.com/microsoft/vscode-cmake-tools/issues/3683#issuecomment-2047766445. 

1. I don't think there is work to do for the output pane. If people want colorization for their output pane, they will have to do something external either way because of the Output Channel not supporting colors from VS Code. There are currently workarounds for this that currently work for a decent amount of people. 
2. The way that we can provide colorization to users that explicitly want it is through tasks, either manually created by them, or by fixing our tasks support to go through the new Terminal API that is being developed here: https://github.com/microsoft/vscode/issues/145234#issuecomment-2045374547

**Comment by gcampbell-msft** [comment]
I've done minimal testing and chatting with the maintainers here https://github.com/microsoft/vscode/issues/145234#issuecomment-2045374547, and while it's not EXACTLY what we want in terms of a simple async-await pattern for invoking a command and getting the exit code, we can definitely use the API to do what we want. Therefore, this API, once officially supported/released, can be used for our task support and we should be able to provide an officially supported way to route tasks (or build) to a terminal and have colorization (assuming their project is set up for colorization in the terminal). 

@sinemakinci1 @microsoft/vscode-cmake FYI.

**Comment by thernstig** [comment]
@gcampbell-msft https://github.com/microsoft/vscode/issues/145234 has been implemented :)

**Comment by gcampbell-msft** [comment]
@thernstig Thanks for the ping. We'll make a note of this so that we have it in mind when considering/prioritizing our work. 😊
