### ISSUE TITLE
Extension display language not right

### ISSUE THREAD

**Issue by xxxbrian** [microsoft/vscode-cmake-tools#3791]
### Brief Issue Summary

The same issue as #3691 , the cmake extension displays the wrong language.

**Comment by xxxbrian** [comment]
Did some digging, this is due to [Code](https://github.com/microsoft/vscode-cmake-tools/blob/cb43dbad1f5e4803ec27845f6f2fa49d73f8b1db/src/util.ts#L673C1-L681C2)
```ts
export function getLocaleId(): string {
    if (typeof (process.env.VSCODE_NLS_CONFIG) === "string") {
        const vscodeNlsConfigJson: any = JSON.parse(process.env.VSCODE_NLS_CONFIG);
        if (typeof (vscodeNlsConfigJson.locale) === "string") {
            return vscodeNlsConfigJson.locale;
        }
    }
    return "en";
}
```

`process.env.VSCODE_NLS_CONFIG` is used to retrieve VSCode NLS. This is an [incorrect usage](https://github.com/microsoft/vscode/issues/78392#issuecomment-518685449) and it seems that this environment variable has been deprecated (as the value it obtains is completely wrong).

**Comment by gcampbell-msft** [comment]
@xxxbrian Thanks for the issue. I took a look at the PR, and based on the API reading I just did, that seems like it will work for that method. However, that almost certainly won't fix the overall issue because we only use that method for the presentation of the pinned commands. 

Have you tried the workaround mentioned in this bug? #3691 

Could you confirm whether the above is the case?
