### ISSUE TITLE
Cmake tools selects on 1.20.6 a different compiler than on 1.18.44 when reconfiguring

### ISSUE THREAD

**Issue by the-programmer** [microsoft/vscode-cmake-tools#4070]
### Brief Issue Summary

The issue is still in the latest version. For full reference see:
https://github.com/microsoft/vscode-cmake-tools/issues/4032

**Comment by gcampbell-msft** [comment]
@the-programmer This is expected. 

We made slight changes to the `cmake.generator` and `cmake.preferredGenerator` settings, as well as the `kit.preferredGenerator` settings. Therefore, there is a chance that you'll need to manually set any of these settings to ensure that you're getting the expected behavior. 

In short, if you set `cmake.generator`, we'll attempt to use it blindly. If you use `cmake.preferredGenerator`, we'll loop over them until we find one on path.

**Comment by the-programmer** [comment]
Ok, thanks for the information.

In case someone else stumbles across this issue, below is how I resolved it. 

When reconfiguring in 1.18.44, the following command gets executed.
```terminal
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Wno-dev --no-warn-unused-cli "-SC:/Development/[...]" "-Bc:/Development/Pedak/[...]" -G Ninja
```

All you need to do is to grab the `-G` parameter (`Ninja` in my case) and set that as `cmake.generator`.
