### ISSUE TITLE
compile_commands.json is not generated for clang-cl kits

### ISSUE THREAD

**Issue by AnonN10** [microsoft/vscode-cmake-tools#4144]
compile_commands.json file which is consumed by clangd is not generated for clang-cl kits, as a workaround one has to use gcc just for that purpose

**Comment by Amy-Li03** [comment]
I can reproduce this issue in CMake Tools release version: v1.19.52, the repro steps as below video:
@gcampbell-msft please confirm if this is a real issue?
![Image](https://github.com/user-attachments/assets/747bc7a8-3d63-427a-88ef-e82ef73c326e)

**Comment by gcampbell-msft** [comment]
@Amy-Li03 @AnonN10 

Based on the documentation here: https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html, `CMAKE_EXPORT_COMPILE_COMMANDS` is only supported for Unix Makefiles generator and Ninja.

Therefore, I believe this is expected. I will close as by design for now, I would encourage you to request this on an issue in the Kitware repository. Thanks!
