### ISSUE TITLE
[loc][Regression] The drop-down lists when adding a preset and selecting a preset are not translated.

### ISSUE THREAD

**Issue by v-frankwang** [microsoft/vscode-cmake-tools#4166]
### Brief Issue Summary

**More info**: This issue is not reproduced in the pre-release version v1.20.17 (pre-release), so it is a regression bug.

**Repro Steps:**

1. Create a folder named demo and open it with vscode.
2. Create a project using the **CMake: Quick Start** command.
3. Reopen the project and run the command **CMake: Add Configure Preset**

**When creating a project:**
**Expected results:**
The contents of the dropdown list when adding a preset and the values of the displayName and description attributes in the added preset code are translated.
![Image](https://github.com/user-attachments/assets/d882b67b-45f2-49af-8b74-8f3277814c9a)

**Actual result:**
The contents of the drop-down list and the values of the displayName and description attributes in the preset code are not translated when the preset is added.
![Image](https://github.com/user-attachments/assets/bacf6ff4-33d7-4f24-b7f7-635d2f1d1ea5)

**When adding a new preset:**
**Expected results:**
When adding a new preset, the content in the drop-down list is correctly translated
![Image](https://github.com/user-attachments/assets/83021414-f9e7-4d8a-9b86-be688f84e356)

**Actual result:**
When adding a new preset, the contents of the drop-down list are not translated
![Image](https://github.com/user-attachments/assets/c010b549-cfd7-466f-9b1d-5fd11ce10229)

### CMake Tools Diagnostics

{
  "os": "win32",
  "vscodeVersion": "1.95.1",
  "cmtVersion": "1.20.22",
  "configurations": [
    {
      "folder": "c:\\Users\\v-frankwang\\Desktop\\test",
      "cmakeVersion": "3.30.4",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {
        "C": "C:/Program Files/Microsoft Visual Studio/2022/IntPreview/VC/Tools/MSVC/14.42.34430/bin/Hostx86/x64/cl.exe",
        "CXX": "C:/Program Files/Microsoft Visual Studio/2022/IntPreview/VC/Tools/MSVC/14.42.34430/bin/Hostx86/x64/cl.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 1,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "helloworld",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}

**Comment by Amy-Li03** [comment]
Verified on CMake Tools v1.20.27(pre-release), this bug is not reproducing, so close it.
Language | When creating a project | When adding a new preset
-- | -- | --
CHS |  ![Image](https://github.com/user-attachments/assets/aa7f83be-70fd-4fb2-90ad-2e6e5259c675) | ![Image](https://github.com/user-attachments/assets/d089f5e3-47c3-418a-8acb-d497713cb4dc)
CHT |  ![Image](https://github.com/user-attachments/assets/ad6bb80b-8ff1-4bae-9748-8843a69f0b5a) | ![Image](https://github.com/user-attachments/assets/baff0329-5c52-4649-96af-32e3334f7df6)
CSY | ![Image](https://github.com/user-attachments/assets/1fc09292-359b-489f-9a40-a8752732b0bc) | ![Image](https://github.com/user-attachments/assets/27cd3cef-0341-4e1a-bbb1-f4b18e8db44d)
DEU | ![Image](https://github.com/user-attachments/assets/16c009c1-5124-4838-98cf-171c74524b44) | ![Image](https://github.com/user-attachments/assets/046e5233-40c8-4978-ad86-6a2a86761c81)
ENU | ![Image](https://github.com/user-attachments/assets/d2db3e4a-d6c2-4bd1-aefd-dda7d2fa6cde) |![Image](https://github.com/user-attachments/assets/ad6e5c3c-0549-4c45-9304-1c256b5b453d)
ESN | ![Image](https://github.com/user-attachments/assets/57cd0c5c-6b3d-4292-ba5e-425354fb5f46) |![Image](https://github.com/user-attachments/assets/4d14c6bf-f793-4dda-9664-552ef2d7e46c)
FRA |![Image](https://github.com/user-attachments/assets/8d83569d-4a5c-4159-8eb3-d5dcd18196e3)  |![Image](https://github.com/user-attachments/assets/94f299bd-f735-457c-8630-7cf8633dabfc)
ITA | ![Image](https://github.com/user-attachments/assets/006afb05-a9d3-45b2-bfea-1205ff608186) |![Image](https://github.com/user-attachments/assets/c2a1bfa7-f3fa-4953-9c76-7fa9b32d250c)
PLK | ![Image](https://github.com/user-attachments/assets/4c9f7dcf-4220-47e0-bb72-f2df6fde3290) |![Image](https://github.com/user-attachments/assets/7787283a-9940-4ca6-90c2-cb416306f532)
PTB |![Image](https://github.com/user-attachments/assets/29bbdd7e-cb6d-4485-984c-592060c2a48b)  |![Image](https://github.com/user-attachments/assets/818b40c9-fa71-4e0d-95fd-bd9d81052d2a)
TRK |![Image](https://github.com/user-attachments/assets/10a67294-d1a6-4474-b057-7461df4cc71b)  |![Image](https://github.com/user-attachments/assets/99b107cb-154d-496d-82a3-d1552d55c949)
RUS |![Image](https://github.com/user-attachments/assets/7354cfa9-bc55-4303-a5b2-52613ad72677)  |![Image](https://github.com/user-attachments/assets/c6f6396e-f3fd-4f56-b5a7-85c92f3cd1a8)
KOR |![Image](https://github.com/user-attachments/assets/834e3c74-dc11-4c70-bdd3-a282ff5c366c)  |![Image](https://github.com/user-attachments/assets/88cda375-8405-4f6c-9070-676d6c5e3a37)
JPN |![Image](https://github.com/user-attachments/assets/9c03a4e7-d368-43ea-b328-8c77f8e9bd31)  |![Image](https://github.com/user-attachments/assets/3ceeba71-bf29-4b34-be38-d6c985b4ac72)
