### ISSUE TITLE
Add a command substitution for target properties

### ISSUE THREAD

**Issue by hillcrest-reedley** [microsoft/vscode-cmake-tools#4188]
### Brief Issue Summary

It would be great if there was a command substitution (for use in launch.json) that could retrieve custom properties set on the target.

### CMake Tools Diagnostics

```shell

```

### Debug Log

```shell

```

**Comment by bpietsch** [comment]
Hi Garrett, thanks for responding to my request. Perhaps the best thing to do would give you an example of what I'm trying to achieve, rather than prescribe a solution...

The use case that prompted my request is that I'm using gdbserver on a raspberry pi to remote debug my project, which I built locally on my laptop via a docker container. Part of this process is establishing an ssh connection to the raspberry pi to communicate with the gdbserver, which I accomplish via a task in tasks.json (which is referenced from my launch.json file). In this case, it would be nice to specify things such as the hostname, ssh key file, etc. as user settings in my project rather than hard coding them in the tasks.json file as this project is shared amongst multiple developers.

**Comment by gcampbell-msft** [comment]
@bpietsch This sounds like something that our extension wouldn't control, but rather VS Code core would control. 

The only way I imagine this would work for us would be to provide a way to get cache variables or target properties (if they are surfaced through the CMake File API) per target and command substitute them. 

However, I think that this would likely be more easily solved by setting environment variables that you open VS Code with, and then using https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables, to access them. Or maybe using this: https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

**Comment by bpietsch** [comment]
You're right, I think I got confused with an earlier solution path I was looking into. I was using a custom cmake target (via add_custom_target) to execute commands to copy the actual build product to the target raspberry pi. I think what I was looking for was a way to then communicate information about that custom target to launch.json, but since it wasn't a "proper" cmake target, the normal variables weren't available. In any case, using the tasks.json approach to do what I was previously attempting to do via cmake reduces the value/need for this ask, so I think it can be closed. If I come up with a more concrete and appropriate request, I'll file a new one. Thanks!
