### ISSUE TITLE
No public API?

### ISSUE THREAD

**Issue by Rettgp** [microsoft/vscode-cmake-tools#494]
Is there a timeline on when public API will be added back in? It appears that the activate() is no longer returning anything and there is a TODO in there.

Thanks and keep up the awesome work!

**Comment by vector-of-bool** [comment]
Yeah, the API will still be up-in-the-air until multi-root lands, since that can change everything about how the extension works. I'm planning to finish up multi-root for 1.2.0.

**Comment by gotschmarcel** [comment]
I would also vote for adding a public API to query compile flags, basically what has been done for the integration into `vscode-cpp-tools`. This would allow many extensions to improve their experience when using them together with CMake, because many of them have to be configured manually which is really painful.

Thanks and keep up the good work :)!

**Comment by MathiasMagnus** [comment]
Yes, hooking in the LaTeX extension would be nice if I build my docs with CMake.

**Comment by c-born** [comment]
I just spent a couple of days trying to work out why nothing I did would get me access to the extension API, eventually went to the source and found the TODO dating back to 13 May 2018.
Is multi-root in now? Is it's implementation stopping turning the API export back on, or is it because the API is expected to change dramatically? And given the time involved before the API is updated, how hard is it to turn on now and try for as much backwards compatibility as possible at a (much?) later date when the changes come in?

**Comment by Deerenaros** [comment]
2k20 is coming, TODO still here. v1.2.3

Are there any plans for the subject?

**Comment by Deerenaros** [comment]
[Here](https://github.com/microsoft/vscode-cmake-tools/pull/973) I created PR but one failed on macOS (?) build. I have no such env to test and fail looks like something strange with `startDebuging` or `C/C++ extension`. I can't find the root of the problem.

**Comment by bobbrow** [comment]
Something changed with `startDebugging` in VS Code without our knowledge.  I disabled the test for now.  We haven't decided on when the API will be re-enabled yet, but it will be sometime after the multi-root support (in PR now) goes in.

**Comment by Deerenaros** [comment]
Thank you for reply. There is one issue i'd caught a little later: api.ts
now should be different while Kit class using here. But i defenitly do not
want to do what becouse at work we chose another way. I will happy if this
little PR would be helpfull.

Happy new year)

вт, 31 дек. 2019 г., 2:07 Bob Brown <notifications@github.com>:

**Comment by bobbrow** [comment]
Thanks.  I think when we do re-enable the API we'll do it similar to how we did it for cpptools.  e.g. create a NPM module for it so that you can pull it in via `package.json` instead of copying `api.ts` into your extensions.

**Comment by Deerenaros** [comment]
Yeah, sounds good. Except solutions when we have no full internet access
due to company politics or technical issues. I realized that vscode cannot
socks5 at all. But anyway I can gather bundle and install them with npm
from "sources".

вт, 31 дек. 2019 г., 19:53 Bob Brown <notifications@github.com>:

**Comment by tritao** [comment]
Any update on this? Would be great to gain access to the public API.

**Comment by bobbrow** [comment]
Please add your 👍 to the first comment in the issue if this is important to you.  With very limited resources available to work on this, that helps us prioritize what we work on next.  Thanks!

**Comment by bobbrow** [comment]
The API has been restored and is available starting in 3.13.18 (pre-release).  To use the API in your extension, you will need to add a dependency to "vscode-cmake-tools" in your `package.json`.  https://www.npmjs.com/package/vscode-cmake-tools
