### ISSUE TITLE
CMAKE_AR-NOTFOUND - cross compilation

### ISSUE THREAD

**Issue by grzesl** [microsoft/vscode-cmake-tools#515]
### Brief Issue Summary

Cross compilling simple program returns error.
I Can`t define path for AR (arm-none-eabi-ar.exe) in cmake-tools.json.

Output of cmake:
CMAKE_AR-NOTFOUND cr CMakeFiles/cmTC_45d16.dir/objects.a @CMakeFiles/cmTC_45d16.dir/objects1.rsp
[cmake]     /bin/sh: CMAKE_AR-NOTFOUND: command not found

**Comment by vector-of-bool** [comment]
Sorry for the delay. Does configuration succeed when configured from the command line?

**Comment by atsju** [comment]
Hi,
I had same issue CMAKE_AR-NOTFOUND on completely different code but updating Cmake to last revision solved the problem.
Please try updating cmake.

**Comment by s-martin** [comment]
I have seen this issue too.
My cross compiler (http://gnutoolchains.com/raspberry/) uses a prefix for all executables (`arm-linux-gnueabihf`).
Since I can only define the C and C++ compiler executables directly in the `cmake-tools.json`, for all other executables like `ar` CMake is unable to find the right executable.

On a quick check yesterday I couldn't find a CMake variable, where I could define such a prefix, but maybe someone can me point to one.
