### ISSUE TITLE
cmake.compileFile or cmake.outline.compileFile

### ISSUE THREAD

**Issue by antmak** [microsoft/vscode-cmake-tools#551]
What is a difference between cmake.compileFile and cmake.outline.compileFile ?

The commad cmake.compileFile "Compile File" works fine.

But the "Compile This File" fails with a "Running the contributed command:'cmake.outline.compileFile' failed." message 

### Platform and Versions

CentOS 7, vscode 1.27.2, vscode-cmake-tools 1.1.2

**Comment by vector-of-bool** [comment]
`cmake.outline.compileFile` is an internal command for the compiling a file from the Project Outline view. The fact that it is visible in the Command Palette is a bug.

**Comment by bobbrow** [comment]
This issue has been addressed in CMake Tools 1.2.0 which is available in the VS Code Marketplace or on the [Releases Page](https://github.com/microsoft/vscode-cmake-tools/releases/tag/v1.2.0)

Because the publisher id has changed, VS Code does not automatically upgrade you yet. The Marketplace team will enable this in the next few days.  If you want to install 1.2.0 now, please make sure you uninstall any earlier versions of CMake Tools manually to avoid any conflicts.
