### ISSUE TITLE
File compilation fails with quotes in compile definitions

### ISSUE THREAD

**Issue by aadnehovda** [microsoft/vscode-cmake-tools#605]
### Brief Issue Summary

Compile single file fails when there are defines with quotes on the command line.

### Example code 

```
project(test)
add_executable(test test.cpp)
add_compile_definitions(TESTVAR="testvar")
```

```
#include <iostream>
int main()
{
    std::cout << TESTVAR;
}
```

### CMake Tools Log
```
cl.exe [...] "testvar\" -c test.cpp
c1xx: fatal error C1083: Cannot open source file: 'testvar" -c test.cpp'
```

### Expected command line

```
cl.exe [...] -DTESTVAR="testvar" [...] -c test.cpp
```

### Platform and Versions

- **Operating System**: Windows (have not tested others yet)
- **CMake Version**: 3.13.1
- **VSCode Version**: 1.29.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Visual C++ 2017

**Comment by KoeMai** [comment]
I tried to reconstruct your problem, but it works in my Dev Enviroment.
I get the output `CL.exe [...] /D "TESTVAR=\"testvar\""[...]`

May be my setup is different:
- What happens if you execute `cmake` on commandline?
- What prefered cmake generator is used?
- What exact visual studio version do you use?
- Do you use the clang compiler? (the compiler flags look like GCC compiler flags)

**Comment by andreeis** [comment]
Triage to 1.4.0 for now, as the potential duplicates https://github.com/microsoft/vscode-cmake-tools/issues/971 and https://github.com/microsoft/vscode-cmake-tools/issues/969
