### ISSUE TITLE
cmake --build devenv command error

### ISSUE THREAD

**Issue by rafmudaf** [microsoft/vscode-cmake-tools#612]
### Brief Issue Summary

`cmake --build` and devenv dont agree on my machine. The added `/m and /property...` flags cause devenv to error.

### Expected:

1. `cmake --build . --target <i choose>`
2. build the proper command for devenv
3. run devenv and/or msbuild without error

### Apparent Behavior:

1. `cmake --build . --target <i choose>`
2. 
```
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/Users/rmudafor/Desktop/openfast/build --config Release --target sphinx-html -- /m /property:GenerateFullPaths=true
[build] 
[build] Microsoft Visual Studio 2015 Version 14.0.25420.1.
[build] Copyright (C) Microsoft Corp. All rights reserved.
[build] Invalid Command Line.
[build] Use:
[build] devenv  [solutionfile | projectfile | anyfile.ext]  [switches]
```

### CMake Tools Log

Where do I find these?

### Developer Tools Log

Where do I find these?

### Platform and Versions

- **Windows 10**: 
- **CMake Version 3.12.3 **: 
- **VSCode Version 1.30**: 
- **CMake Tools Extension Version 1.1.3**: 

### Other Notes/Information

Are these generator flags required?
https://github.com/vector-of-bool/vscode-cmake-tools/blob/b3a7aca1f86052ef94111163514906474c3d1f47/src/driver.ts#L725

**Comment by KoeMai** [comment]
I tried to reconstuct your problem, but it didn´t work.
Which visual studio version do you have? I tried with VS 2015 community.

What happens if you call the following command from commandline?
`"C:\Program Files\CMake\bin\cmake.EXE" --build c:/Users/rmudafor/Desktop/openfast/build --config Release --target sphinx-html -- /m /property:GenerateFullPaths=true`
