### ISSUE TITLE
MSYS2 MINGW not working , added PATH

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [microsoft/vscode-cmake-tools#627]
![image](https://user-images.githubusercontent.com/25037295/50735362-da0ed200-11e8-11e9-97ef-4e0a9f8538a8.png)

relates to https://github.com/vector-of-bool/vscode-cmake-tools/issues/309 but I added PATH already
![image](https://user-images.githubusercontent.com/25037295/50735387-4093f000-11e9-11e9-9246-0f6a7ac778f3.png)

Funny enough , on my D:\ I found this
![image](https://user-images.githubusercontent.com/25037295/50735457-640b6a80-11ea-11e9-981e-b5d42501b974.png)

**Comment by andreeis** [comment]
Can you try the latest release? If you still have this problem, it would help to also provide a repro or at least a verbose CMake Tools log.
Note that CMake server is deprecated and we recommend fileApi, check if you have any explicit settings for CMake server. Otherwise, our defaults will chose the right thing now.
