### ISSUE TITLE
Workspace settings "cmake.configureSettings" not recognized

### ISSUE THREAD

**Issue by Taugeshtu** [microsoft/vscode-cmake-tools#630]
### Brief Issue Summary

User settings:

```
"cmake.configureSettings": {
	"FUNK" : "meh"
}
```

Workspace settings:

```
"cmake.configureSettings": {
	"FUNK" : "yasss"
}
```

And inside cmake file:

> message( "Do you FUNK? ${FUNK}" )

### Expected:

> Do you FUNK? yasss

### Apparent Behavior:

> Do you FUNK? meh

### Platform and Versions

- **Operating System**: Windows 10
- **VSCode Version**: 1.30.2
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Visual C++ 2017

### Other Notes/Information

Moreover, if I clear user settings I get no FUNK at all. It's not a critical issue for me (because what I want to put into configure options - OpenCV, boost, other libs paths and include dirs - is shared and of the same version for all the projects), but is worth looking into, as I gather.

Thank you for making and maintaining this extension! It's such a relief to escape from cumbersome, heavy full-blown Visual Studio into Code :)

**Comment by jclay** [comment]
So my understanding is that there are two issues here:

1) When you only set this in the workspace settings, the variable doesn't get set. I have a similar setting in only my workspace settings (`cmake.configureSettings` not set at all in user settings), and it works as expected. I often find I need to do some combination of `> Cmake: Reset Extensions tools state` and `> Reload window` since that will trigger a CMake server restart. Note, a great way to debug what's getting set is to set `"cmake.useCMakeServer": true` (I do this in User settings, although it shouldn't matter).

2) It looks like you expect user settings to take precedence over workspace. I haven't verified, but I suspect it is the opposite. Given a duplicate setting in workspace and user, it would make sense that VSCode gives workspace precedence here allowing you to override for specific project related settings. You could verify with something like setting editor font size in both and see which takes precedence.

Regarding your use case for linking libs, have you checked out VCPKG? If that doesn't suit your use case, I would simply modify your kit to include your own toolchain file which sets the variables you need for all projects. That could look something like this:

```json
  {
    "name": "VS2017 - amd64_x86",
    "visualStudio": "VisualStudio.15.0",
    "visualStudioArchitecture": "amd64_x86",
    "preferredGenerator": {
      "name": "Visual Studio 15 2017"
    },
    "toolchainFile": "${workspaceRoot}/cmake/toolchains/windows.cmake"
  },
```

```
# your toolchain file:
  set(USE_CUDA "OFF" CACHE INTERNAL "" FORCE)
  set(OpenCV_DIR "C:/etc/etc/" CACHE PATH "")
```

**Comment by bobbrow** [comment]
I wasn't able to reproduce the problem with the latest version of VS Code and 1.1.3 of the extension. Please let us know if you continue to have a problem with this.

**Comment by RReverser** [comment]
I'm having exactly the same issue a year since this one was closed, so I suspect it still exists. Just like @jclay mentioned, only resetting state or reloading window helps CMake to pick up the new `configureSettings` - otherwise they seem to be cached and any changes are ignored when running "CMake - Configure".

**Comment by bobbrow** [comment]
We're tracking this with #1127

**Comment by RReverser** [comment]
Thanks, I'll subscribe there.
