### ISSUE TITLE
Wrong `standard` pass to cpp-tools

### ISSUE THREAD

**Issue by xVanTuring** [microsoft/vscode-cmake-tools#639]
### Expected:

__cplusplus should not be defined in c file, void pointer should cast  without error. Building is fine, but you know...

### Apparent Behavior:
![screenshot from 2019-01-22 22-15-46](https://user-images.githubusercontent.com/11146248/51541290-6bda3880-1e93-11e9-9628-c1bd784b52a6.png)

with default standard [`c++17`](https://github.com/vector-of-bool/vscode-cmake-tools/blob/5f7bca659901ce2ecd0eab27302f02e3208e0d98/src/cpptools.ts#L218), it ends up with cpp-tooling miss-reporting error

**Comment by bobbrow** [comment]
This issue has been addressed in CMake Tools 1.2.0 which is available in the VS Code Marketplace or on the [Releases Page](https://github.com/microsoft/vscode-cmake-tools/releases/tag/v1.2.0)

Because the publisher id has changed, VS Code does not automatically upgrade you yet. The Marketplace team will enable this in the next few days.  If you want to install 1.2.0 now, please make sure you uninstall any earlier versions of CMake Tools manually to avoid any conflicts.
