### ISSUE TITLE
Multiple configure runs in parallel

### ISSUE THREAD

**Issue by gotschmarcel** [microsoft/vscode-cmake-tools#641]
### Brief Issue Summary

It’s possible to run CMake configure multiple times in parallel which in the end leads to an error. 

### Expected:

It should not be possible to run cmake multiple times in parallel. 

### Platform and Versions

- **Operating System**: macOS Mojave
- **CMake Version**: 3.12.1
- **VSCode Version**: 1.30.2
- **CMake Tools Extension Version**: 1.1.3

**Comment by bobbrow** [comment]
This issue has been addressed in CMake Tools 1.2.0 which is available in the VS Code Marketplace or on the [Releases Page](https://github.com/microsoft/vscode-cmake-tools/releases/tag/v1.2.0)

Because the publisher id has changed, VS Code does not automatically upgrade you yet. The Marketplace team will enable this in the next few days.  If you want to install 1.2.0 now, please make sure you uninstall any earlier versions of CMake Tools manually to avoid any conflicts.
