### ISSUE TITLE
Scan for Kit: does not detect clang

### ISSUE THREAD

**Issue by nackdai** [microsoft/vscode-cmake-tools#732]
I installed clang, cmake and vscode.
And, I put path to clang, cmake.
After that, I installed cmake-tools vscode extension.

But, Scan for Kit does not detect clang automatically.

My environment is below.

**Ubuntu 18.04 LTS
clang 8.0.0 : /usr/local/clang_8.0.0
cmake 3.15.0 : /usr/local/cmake
vscode 1.37.0**

It seems this problem is similar to #335.

**Comment by sean-mcmanus** [comment]
Same here -- I see clang 3.8.1 detected by not clang 6. Manually setting the CMAKE_CXX_COMPILER and CMAKE_C_COMPILER appears to have worked around the issue, except every time the workspace is reloaded it keeps re-showing the "Select a Kit" dropdown (selecting [Unspecified] fixes it) -- seems like it should be saving the "Unspecified" state instead of continually reprompting.

**Comment by guoren97** [comment]
You can manually add the clang information in the CMakeTools config file, and the CMakeTools will automatically reload this file and find your clang.
~/.local/share/CMakeTools/cmake-tools-kits.json

**Comment by nackdai** [comment]
I re-installed clang8 via apt get, and then Kit could detect installed clang.
Sorry for bothering you
