### ISSUE TITLE
Need to change ${workspaceRoot} to ${workspaceFolder} in vs code settings code.

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode-cmake-tools#740]
### Brief Issue Summary

In settings.json in VS Code, after a fresh install of cmake-tools, ${workspaceRoot} is inserted into the Cmake: Build Directory setting and the Cmake: Source Directory. But this has been replaced by ${workspaceFolder} by the VS Code team.

### Expected:
${workspaceFolder} should appear instead going forward.

**Comment by bobbrow** [comment]
This issue has been addressed in CMake Tools 1.2.0 which is available in the VS Code Marketplace or on the [Releases Page](https://github.com/microsoft/vscode-cmake-tools/releases/tag/v1.2.0)

Because the publisher id has changed, VS Code does not automatically upgrade you yet. The Marketplace team will enable this in the next few days.  If you want to install 1.2.0 now, please make sure you uninstall any earlier versions of CMake Tools manually to avoid any conflicts.
