### ISSUE TITLE
Avoid using workspace.rootPath

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-cmake-tools#748]
This extension appears to be using the `workspace.rootPath` API. This is a deprecated property and may not work as expected. Please use `workspaceFolders` instead. More info:  https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#eliminating-rootpath

https://github.com/microsoft/vscode/issues/69335

**Comment by bobbrow** [comment]
I created a PR for this.

**Comment by bobbrow** [comment]
CMake Tools 1.2.0 is available in the VS Code Marketplace or on the [Releases Page](https://github.com/microsoft/vscode-cmake-tools/releases/tag/v1.2.0)

Because the publisher id has changed, VS Code does not automatically upgrade you yet. The Marketplace team will enable this in the next few days.  If you want to install 1.2.0 now, please make sure you uninstall any earlier versions of CMake Tools manually to avoid any conflicts.
