### ISSUE TITLE
Environmental variables within config settings not expanding

### ISSUE THREAD

**Issue by CodeAnxiety** [microsoft/vscode-cmake-tools#767]
### Brief Issue Summary

Environmental variables within config settings may not expand correctly, possibly due to the variable name normalization that occurs before expansion.

### Expected:
1. Assume you are trying to configure CMakeTools to work with [microsoft/vcpkg](https://github.com/microsoft/vcpkg), for example.
2. Assume you have an environmental variable named `VCPKG_ROOT` that points your `vcpkg` directory.
3. Configure CMakeTools as such inside your workspace's `settings.json`. 🐱‍👤
```json
{
  "cmake.configureSettings": {
    "CMAKE_TOOLCHAIN_FILE": "${env:VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
  }
}
```
4. Perform a clean configure. `>CMake: Delete cached build settings and reconfigure`
5. Have your `find_package` calls auto-magically work! 🧙‍♂️

### Apparent Behavior:

1. Perform expected steps 1-4.
2. Watch as CMake fails with an error stating that the toolchain file could not be found. 😱

### CMake Tools Log
```
...
[cmake] CMake Error at c:/cmake/share/cmake-3.15/Modules/CMakeDetermineSystem.cmake:99 (message):
[cmake]   Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:2 (project)
...
```

### Platform and Versions
- **Operating System**:  Windows
- **CMake Version**: 3.15.2
- **VSCode Version**: 1.38.0
- **CMake Tools Extension Version**:  1.1.3
- **Compiler/Toolchain**: Visual C++ 2019

### Other Notes/Information
May be related to #489, but after a brief glance I'm not seeing anything in the related fix (af0f6f024ba43eea5f21b76e1cf8427bf4a9fec4) that suggests that this is the same issue. 

As best as I can tell, this is being caused, in part, by variable names being normalized (which means converting to lowercase on Windows) before expansion. I.e. ${env:NAME} is being treated as ${env:name}.

https://github.com/microsoft/vscode-cmake-tools/blob/bc9f08f2dca95c0f17ae06b30bd36687266f112c/src/expand.ts#L92
https://github.com/microsoft/vscode-cmake-tools/blob/bc9f08f2dca95c0f17ae06b30bd36687266f112c/src/expand.ts#L100

However, the map (`env`) containing the values does not contain keys that were also normalized, causing the lookup with the normalized name to return `undefined`.

I'm not aware of the reasoning behind normalizing the variable names, but as best I can tell there are at least four possible options for a fix/workaround.
1. Normalize (and cache) all the key names within `env` so the lookup works as expected. 😁
2. Change the previously mentioned source code lines to resemble the following: 😅
```typescript
    const repl = env[varname] || env[normalizeEnvironmentVarname(varname)] || '';
```
3. Change your environment variables to be lower case, matching the assumption of `normalizeEnvironmentVarname`. 😆
4. Hard-code your configuration settings so you don't even need the expansion to work. 🤔

**Comment by alan-wr** [comment]
@CodeAnxiety 
I set toolchainfile on cmake-tools-kits.json, and the ENV can be expanded. (and pre-define variable is fine, I test workspaceFolder, but failed to paser config variable.)

Sample:
CMake: Edit User-Local CMake Kits.
Add tool kits as
  {
    "name": "my env tool kits",
    "toolchainFile": "${env:SHELL}/toolkit/include/mk/toolchain.cmake"
  },

The env:SHELL will be parsed as /bin/bash
---
toolchain file: /bin/bash/toolkit/include/mk/toolchain.cmake
---

**Comment by btgoodwin** [comment]
Any update on this?  I'm using macOS Code 1.50.1 and I cannot seem to get any cmake combination of variable expansion to work so that I can use multi-root workspace `${workspaceFolder:Name}` in things like `cmake.configureSettings`:

```json
{
  "folders": [
    { "name": "Other", "path": "other_dir" }
  ],
  "settings": {
    "cmake.configureSettings": {
      "OTHER_PROJECT_DIR": "${workspaceFolder:Other}"
    }
  }
}
```

The above results in `-DOTHER_PROJECT_DIR:STRING=${workspaceFolder:Other}` which isn't helpful.  Incredibly if I pick a variable that doesn't exist, I do get an expansion error.

Based on the OP I tried setting a cmake variable (`cmake.environment` that was lower-cased and then expand that, but I get the same result where it inserts the actual text `${env:dummy_test}` for the variable rather than the expanded value.  It's as if somewhere along the line it is expanding the value, but then it moves forward using the un-expanded variant.

**Comment by lygstate** [comment]
Not expanding or not expanding propery?

**Comment by btgoodwin** [comment]
> Not expanding or not expanding propery?

I apologize, I no longer have the environment setup where I was trying to debug this and I don't understand the your question, I think.  If variables are not expanding to their penultimate definitions then the variable expansion is not working properly.  So, both?

The issues here are related in that they're both VSCode JSON spec variables that we're trying to expand within the JSON to whatever the definition is supposed to be.  In the OP's case, the `${env:...}` was expected to expand to an environment-defined value.  In my case, the `${workspaceFolder:...}` was expected to expand to the folder `name:`, a workspace-defined value.  In both cases we found the variables seemed to be evaluated and then the result ignored rather than substituted into the reference location.

I reviewed #2236's comments but it's unclear if it will help at least in my issue (being able to use `workspaceFolder` in configuring the CMAKE environment).  I'll keep an eye out for the release where this goes in though and see if I can carve off some time to repro my environment.

I see this has been getting pushed out several times over the last year.  Do you have an ETA for when this will be in a release or what release number it will be?

**Comment by lygstate** [comment]
> > Not expanding or not expanding propery?
> 
> I apologize, I no longer have the environment setup where I was trying to debug this and I don't understand the your question, I think. If variables are not expanding to their penultimate definitions then the variable expansion is not working properly. So, both?
> 
> The issues here are related in that they're both VSCode JSON spec variables that we're trying to expand within the JSON to whatever the definition is supposed to be. In the OP's case, the `${env:...}` was expected to expand to an environment-defined value. In my case, the `${workspaceFolder:...}` was expected to expand to the folder `name:`, a workspace-defined value. In both cases we found the variables seemed to be evaluated and then the result ignored rather than substituted into the reference location.
> 
> I reviewed #2236's comments but it's unclear if it will help at least in my issue (being able to use `workspaceFolder` in configuring the CMAKE environment). I'll keep an eye out for the release where this goes in though and see if I can carve off some time to repro my environment.
> 
> I see this has been getting pushed out several times over the last year. Do you have an ETA for when this will be in a release or what release number it will be?

Oh, do you means getting the following configure to be works?
That my PR are not related
```
{
  "folders": [
    { "name": "Other", "path": "other_dir" }
  ],
  "settings": {
    "cmake.configureSettings": {
      "OTHER_PROJECT_DIR": "${workspaceFolder:Other}"
    }
  }
}
```

**Comment by andreeis** [comment]
Closing the ticket. If anyone sees any such symptoms again please reactivate and give plenty of info to help us reproduce on our side and investigate.
